package pe.gob.trabajo.pcd.modelo.dominio;

// Generated 27/01/2011 05:11:53 PM by Hibernate Tools 3.4.0.Beta1


/**
 * TiprfPrfsnalIdioma generated by hbm2java
 */
public class ProfesionalIdioma extends BeanEntidadGenericoAutogeneradoValidable implements java.io.Serializable {
	
	private static final long serialVersionUID = 7526454825249453196L;
	
	private Idioma idioma;
	private Profesional profesional;
	private Integer comprensionAuditiva;
	private Integer comprensionLectura;
	private Integer hablar;
	private Integer escribir;
	private Long overall;
	private Integer nativo;
	private NivelIdioma nivelIdioma;
	
	public NivelIdioma getNivelIdioma() {
		return nivelIdioma;
	}
	public void setNivelIdioma(NivelIdioma nivelIdioma) {
		this.nivelIdioma = nivelIdioma;
	}
	public Idioma getIdioma() {
		return idioma;
	}
	public void setIdioma(Idioma idioma) {
		this.idioma = idioma;
	}
	public Profesional getProfesional() {
		return profesional;
	}
	public void setProfesional(Profesional profesional) {
		this.profesional = profesional;
	}
	public Integer getComprensionAuditiva() {
		return comprensionAuditiva;
	}
	public void setComprensionAuditiva(Integer comprensionAuditiva) {
		this.comprensionAuditiva = comprensionAuditiva;
	}
	public Integer getComprensionLectura() {
		return comprensionLectura;
	}
	public void setComprensionLectura(Integer comprensionLectura) {
		this.comprensionLectura = comprensionLectura;
	}
	public Integer getHablar() {
		return hablar;
	}
	public void setHablar(Integer hablar) {
		this.hablar = hablar;
	}
	public Integer getEscribir() {
		return escribir;
	}
	public void setEscribir(Integer escribir) {
		this.escribir = escribir;
	}
	public Long getOverall() {
		return overall;
	}
	public void setOverall(Long overall) {
		this.overall = overall;
	}
	public Integer getNativo() {
		return nativo;
	}
	public void setNativo(Integer nativo) {
		this.nativo = nativo;
	}
	
	public Boolean getIdiomaNativo () {
		boolean retorno = false;
		
		if ( nativo!=null && nativo.equals(1)) {
			retorno = true;
		}
		return retorno;
	}
	
	public void setIdiomaNativo(Boolean idiomaNativo) {
		if (idiomaNativo) {
			this.nativo = 1;
		} else {
			this.nativo = 0;
		}
	}
	
}
