package pe.gob.trabajo.pcd.modelo.dominio;

// Generated 28/01/2011 10:09:44 AM by Hibernate Tools 3.4.0.Beta1

/**
 * TiprmRelacionTecnologia generated by hbm2java
 */
public class RelacionTecnologia extends BeanEntidadGenerico implements java.io.Serializable {
	
	private static final long serialVersionUID = 5131702394985456944L;
	
	private RelacionTecnologiaId id;
	private EspecialidadProfesional especialidadProfesionalOrigen;
	private EspecialidadProfesional especialidadProfesionalDestino;
	private TipoRelacionTecnologia tipoRelacionTecnologia;
	private String comentarios;
	private Double peso;
	
	public RelacionTecnologiaId getId() {
		return id;
	}
	public void setId(RelacionTecnologiaId id) {
		this.id = id;
	}
	public EspecialidadProfesional getEspecialidadProfesionalOrigen() {
		return especialidadProfesionalOrigen;
	}
	public void setEspecialidadProfesionalOrigen(
			EspecialidadProfesional especialidadProfesionalOrigen) {
		this.especialidadProfesionalOrigen = especialidadProfesionalOrigen;
	}
	public EspecialidadProfesional getEspecialidadProfesionalDestino() {
		return especialidadProfesionalDestino;
	}
	public void setEspecialidadProfesionalDestino(
			EspecialidadProfesional especialidadProfesionalDestino) {
		this.especialidadProfesionalDestino = especialidadProfesionalDestino;
	}
	public TipoRelacionTecnologia getTipoRelacionTecnologia() {
		return tipoRelacionTecnologia;
	}
	public void setTipoRelacionTecnologia(
			TipoRelacionTecnologia tipoRelacionTecnologia) {
		this.tipoRelacionTecnologia = tipoRelacionTecnologia;
	}
	public String getComentarios() {
		return comentarios;
	}
	public void setComentarios(String comentarios) {
		this.comentarios = comentarios;
	}
	public Double getPeso() {
		return peso;
	}
	public void setPeso(Double peso) {
		this.peso = peso;
	}
}
