package pe.gob.trabajo.pcd.modelo.dominio;

// Generated 27/01/2011 05:11:53 PM by Hibernate Tools 3.4.0.Beta1


/**
 * TiprfPrfsnalExprncaEspcldad generated by hbm2java
 */
public class ExperienciaEspecialidad extends BeanEntidadGenericoAutogeneradoValidable implements java.io.Serializable {
	
	private static final long serialVersionUID = -6379442838521448216L;
	
//	private EspecialidadProfesional especialidadProfesional;
	private Profesional profesional;
	private Integer meses;
	private Integer autoevaluacion;
	private Integer calificacion;
	private String comentarios;
	
	private String idOcupacion;
	private String descripcionOcupacion;
	
	private Integer principal;
	
//	public EspecialidadProfesional getEspecialidadProfesional() {
//		return especialidadProfesional;
//	}
//	public void setEspecialidadProfesional(
//			EspecialidadProfesional especialidadProfesional) {
//		this.especialidadProfesional = especialidadProfesional;
//	}
	public Profesional getProfesional() {
		return profesional;
	}
	public void setProfesional(Profesional profesional) {
		this.profesional = profesional;
	}
	public Integer getMeses() {
		return meses;
	}
	public void setMeses(Integer meses) {
		this.meses = meses;
	}
	public Integer getAutoevaluacion() {
		return autoevaluacion;
	}
	public void setAutoevaluacion(Integer autoevaluacion) {
		this.autoevaluacion = autoevaluacion;
	}
	public Integer getCalificacion() {
		return calificacion;
	}
	public void setCalificacion(Integer calificacion) {
		this.calificacion = calificacion;
	}
	public String getComentarios() {
		return comentarios;
	}
	public void setComentarios(String comentarios) {
		this.comentarios = comentarios;
	}
	public String getIdOcupacion() {
		return idOcupacion;
	}
	public void setIdOcupacion(String idOcupacion) {
		this.idOcupacion = idOcupacion;
	}
	public String getDescripcionOcupacion() {
		return descripcionOcupacion;
	}
	public void setDescripcionOcupacion(String descripcionOcupacion) {
		this.descripcionOcupacion = descripcionOcupacion;
	}
	/**
	 * @return the principal
	 */
	public Integer getPrincipal() {
		return principal;
	}
	/**
	 * @param principal the principal to set
	 */
	public void setPrincipal(Integer principal) {
		this.principal = principal;
	}
	
	public Boolean getOcupacionPrincipal () {
		boolean retorno = false;
		
		if ( principal!=null && principal.equals(1)) {
			retorno = true;
		}
		return retorno;
	}
	
	public void setOcupacionPrincipal(Boolean idiomaNativo) {
		if (idiomaNativo) {
			this.principal = 1;
		} else {
			this.principal = 0;
		}
	}
}
