package pe.gob.trabajo.pcd.modelo.dominio;


// Generated 27/01/2011 05:11:53 PM by Hibernate Tools 3.4.0.Beta1


/**
 * TiprfPrfsnalCertificacion generated by hbm2java
 */
public class Empleador extends BeanEntidadGenericoAutogenerado implements java.io.Serializable {


	private static final long serialVersionUID = -24423667681133885L;
	
	private Establecimiento establecimiento;
	
	private String flag;

	public Establecimiento getEstablecimiento() {
		return establecimiento;
	}

	public void setEstablecimiento(Establecimiento establecimiento) {
		this.establecimiento = establecimiento;
	}

	public String getFlag() {
		return flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

}
