package pe.gob.trabajo.pcd.modelo.dominio;


/**
 * PersonaCondicionesTrabajo generated by hbm2java
 */
public class PersonaCondicionesTrabajo extends BeanEntidadGenericoAutogenerado
		implements java.io.Serializable {

	private static final long serialVersionUID = -6937544418664685727L;

	private Persona persona;
	
	private Integer jornada;
	private Integer interior;
	private Integer estabilidadLugar;
	private Integer actividad;
	private Integer temperatura;
	private Integer ruido;
	private Integer limpieza;
	private Integer tarea;
	private Integer espacio;
	private Integer grupo;
	private Integer uniforme;
	private Integer palabras;
	private Integer numeros;
	private Integer transporte;
	private Integer compania;
	/**
	 * @return the persona
	 */
	public Persona getPersona() {
		return persona;
	}
	/**
	 * @param persona the persona to set
	 */
	public void setPersona(Persona persona) {
		this.persona = persona;
	}
	/**
	 * @return the jornada
	 */
	public Integer getJornada() {
		return jornada;
	}
	/**
	 * @param jornada the jornada to set
	 */
	public void setJornada(Integer jornada) {
		this.jornada = jornada;
	}
	/**
	 * @return the interior
	 */
	public Integer getInterior() {
		return interior;
	}
	/**
	 * @param interior the interior to set
	 */
	public void setInterior(Integer interior) {
		this.interior = interior;
	}
	/**
	 * @return the estabilidadLugar
	 */
	public Integer getEstabilidadLugar() {
		return estabilidadLugar;
	}
	/**
	 * @param estabilidadLugar the estabilidadLugar to set
	 */
	public void setEstabilidadLugar(Integer estabilidadLugar) {
		this.estabilidadLugar = estabilidadLugar;
	}
	/**
	 * @return the actividad
	 */
	public Integer getActividad() {
		return actividad;
	}
	/**
	 * @param actividad the actividad to set
	 */
	public void setActividad(Integer actividad) {
		this.actividad = actividad;
	}
	/**
	 * @return the temperatura
	 */
	public Integer getTemperatura() {
		return temperatura;
	}
	/**
	 * @param temperatura the temperatura to set
	 */
	public void setTemperatura(Integer temperatura) {
		this.temperatura = temperatura;
	}
	/**
	 * @return the ruido
	 */
	public Integer getRuido() {
		return ruido;
	}
	/**
	 * @param ruido the ruido to set
	 */
	public void setRuido(Integer ruido) {
		this.ruido = ruido;
	}
	/**
	 * @return the limpieza
	 */
	public Integer getLimpieza() {
		return limpieza;
	}
	/**
	 * @param limpieza the limpieza to set
	 */
	public void setLimpieza(Integer limpieza) {
		this.limpieza = limpieza;
	}
	/**
	 * @return the tarea
	 */
	public Integer getTarea() {
		return tarea;
	}
	/**
	 * @param tarea the tarea to set
	 */
	public void setTarea(Integer tarea) {
		this.tarea = tarea;
	}
	/**
	 * @return the espacio
	 */
	public Integer getEspacio() {
		return espacio;
	}
	/**
	 * @param espacio the espacio to set
	 */
	public void setEspacio(Integer espacio) {
		this.espacio = espacio;
	}
	/**
	 * @return the grupo
	 */
	public Integer getGrupo() {
		return grupo;
	}
	/**
	 * @param grupo the grupo to set
	 */
	public void setGrupo(Integer grupo) {
		this.grupo = grupo;
	}
	/**
	 * @return the uniforme
	 */
	public Integer getUniforme() {
		return uniforme;
	}
	/**
	 * @param uniforme the uniforme to set
	 */
	public void setUniforme(Integer uniforme) {
		this.uniforme = uniforme;
	}
	/**
	 * @return the palabras
	 */
	public Integer getPalabras() {
		return palabras;
	}
	/**
	 * @param palabras the palabras to set
	 */
	public void setPalabras(Integer palabras) {
		this.palabras = palabras;
	}
	/**
	 * @return the numeros
	 */
	public Integer getNumeros() {
		return numeros;
	}
	/**
	 * @param numeros the numeros to set
	 */
	public void setNumeros(Integer numeros) {
		this.numeros = numeros;
	}
	/**
	 * @return the transporte
	 */
	public Integer getTransporte() {
		return transporte;
	}
	/**
	 * @param transporte the transporte to set
	 */
	public void setTransporte(Integer transporte) {
		this.transporte = transporte;
	}
	/**
	 * @return the compania
	 */
	public Integer getCompania() {
		return compania;
	}
	/**
	 * @param compania the compania to set
	 */
	public void setCompania(Integer compania) {
		this.compania = compania;
	}
	
}
