--Ejecutar después de regenerar la BD con create-drop
set define off;
	 
	Insert into PDTBC_ROLUSUARIO(N_CODROL,V_DSCRPCON) values (1,'Administrador');
	Insert into PDTBC_ROLUSUARIO(N_CODROL,V_DSCRPCON) values (2,'Consultor ABE');
	Insert into PDTBC_ROLUSUARIO(N_CODROL,V_DSCRPCON) values (3,'Consultor de empleo');
	Insert into PDTBC_ROLUSUARIO(N_CODROL,V_DSCRPCON) values (4,'Postulante');
	Insert into PDTBC_ROLUSUARIO(N_CODROL,V_DSCRPCON) values (5,'Empleador');
	Insert into PDTBC_ROLUSUARIO(N_CODROL,V_DSCRPCON) values (6,'Consultor CUL');
	
	Insert into PDTBC_PERSONA (N_CODPRSNA,V_CODTPODCM,V_APPTRNO,V_APMTRNO,V_NOMBRES) values (1,'03','Perez','Lopez','Andres');
	Insert into PDTBC_PERSONA (N_CODPRSNA,V_CODTPODCM,V_APPTRNO,V_APMTRNO,V_NOMBRES) values (2,'03','Galvez','Mota','Jose');
	Insert into PDTBC_PERSONA (N_CODPRSNA,V_CODTPODCM,V_APPTRNO,V_APMTRNO,V_NOMBRES) values (3,'03','Montes','Quiroz','Manuel');
	

	Insert into PDTBC_USUARIO (N_CODUSRO,N_CODPRSNA,N_CODROL,V_NOMBREUSR,V_CLAVEUSR,C_ESTRGSTRO) 
	values ('1','1','1','admin','admin','A');
	Insert into PDTBC_USUARIO (N_CODUSRO,N_CODPRSNA,N_CODROL,V_NOMBREUSR,V_CLAVEUSR,C_ESTRGSTRO) 
	values ('2','2','2','operador','123','A');
	Insert into PDTBC_USUARIO (N_CODUSRO,N_CODPRSNA,N_CODROL,V_NOMBREUSR,V_CLAVEUSR,C_ESTRGSTRO) 
	values ('3','3','3','consultor','123','A');
	
	SELECT SEQ_PRSNAID.nextval FROM DUAL;
	SELECT SEQ_PRSNAID.nextval FROM DUAL;
	SELECT SEQ_PRSNAID.nextval FROM DUAL;
	
	SELECT SEQ_USROID.nextval FROM DUAL;
	SELECT SEQ_USROID.nextval FROM DUAL;
	SELECT SEQ_USROID.nextval FROM DUAL;
	
  
  --Tipo empleo
	INSERT INTO PDTBC_PARAMETRO(N_CODPRMTRO,V_DSCRMNDOR, V_NOMBRE, V_DESVALOR, N_NUMORDEN, C_ESTRGSTRO, N_VRSNTRNSC)
	VALUES(SEQ_PRMTROID.nextval,'TIPO_EMPLEO', 'Tipo empleo', 'Tiempo completo', 1, 'A',1);

	INSERT INTO PDTBC_PARAMETRO(N_CODPRMTRO,V_DSCRMNDOR, V_NOMBRE, V_DESVALOR, N_NUMORDEN, C_ESTRGSTRO, N_VRSNTRNSC)
	VALUES(SEQ_PRMTROID.nextval,'TIPO_EMPLEO', 'Tipo empleo', 'Medio tiempo', 2, 'A',1);
  
  	--Estado civil
	INSERT INTO PDTBC_PARAMETRO(N_CODPRMTRO,V_DSCRMNDOR, V_NOMBRE, V_DESVALOR, N_NUMORDEN, C_ESTRGSTRO, N_VRSNTRNSC)
	VALUES(SEQ_PRMTROID.nextval,'ESTADO_CIVIL', 'Estado civil', 'Soltero (a)', 1, 'A',1);

	INSERT INTO PDTBC_PARAMETRO(N_CODPRMTRO,V_DSCRMNDOR, V_NOMBRE, V_DESVALOR, N_NUMORDEN, C_ESTRGSTRO, N_VRSNTRNSC)
	VALUES(SEQ_PRMTROID.nextval,'ESTADO_CIVIL', 'Estado civil', 'Casado (a)', 2, 'A',1);

	INSERT INTO PDTBC_PARAMETRO(N_CODPRMTRO,V_DSCRMNDOR, V_NOMBRE, V_DESVALOR, N_NUMORDEN, C_ESTRGSTRO, N_VRSNTRNSC)
	VALUES(SEQ_PRMTROID.nextval,'ESTADO_CIVIL', 'Estado civil', 'Viudo (a)', 3, 'A',1);

	INSERT INTO PDTBC_PARAMETRO(N_CODPRMTRO,V_DSCRMNDOR, V_NOMBRE, V_DESVALOR, N_NUMORDEN, C_ESTRGSTRO, N_VRSNTRNSC)
	VALUES(SEQ_PRMTROID.nextval,'ESTADO_CIVIL', 'Estado civil', 'Divorciado (a)', 4, 'A',1);

	INSERT INTO PDTBC_PARAMETRO(N_CODPRMTRO,V_DSCRMNDOR, V_NOMBRE, V_DESVALOR, N_NUMORDEN, C_ESTRGSTRO, N_VRSNTRNSC)
	VALUES(SEQ_PRMTROID.nextval,'ESTADO_CIVIL', 'Estado civil', 'Separado (a)', 5, 'A',1);

	INSERT INTO PDTBC_PARAMETRO(N_CODPRMTRO,V_DSCRMNDOR, V_NOMBRE, V_DESVALOR, N_NUMORDEN, C_ESTRGSTRO, N_VRSNTRNSC)
	VALUES(SEQ_PRMTROID.nextval,'ESTADO_CIVIL', 'Estado civil', 'Conviviente', 6, 'A',1);
  
  --Nivel Idioma
	INSERT INTO PDTBC_PARAMETRO(N_CODPRMTRO,V_DSCRMNDOR, V_NOMBRE, V_DESVALOR, N_NUMORDEN, C_ESTRGSTRO, N_VRSNTRNSC)
	VALUES(SEQ_PRMTROID.nextval,'NIVEL_IDIOMA', 'Nivel Idioma', 'Básico', 1, 'A',1);

	INSERT INTO PDTBC_PARAMETRO(N_CODPRMTRO,V_DSCRMNDOR, V_NOMBRE, V_DESVALOR, N_NUMORDEN, C_ESTRGSTRO, N_VRSNTRNSC)
	VALUES(SEQ_PRMTROID.nextval,'NIVEL_IDIOMA', 'Nivel Idioma', 'Intermedio', 2, 'A',1);

	INSERT INTO PDTBC_PARAMETRO(N_CODPRMTRO,V_DSCRMNDOR, V_NOMBRE, V_DESVALOR, N_NUMORDEN, C_ESTRGSTRO, N_VRSNTRNSC)
	VALUES(SEQ_PRMTROID.nextval,'NIVEL_IDIOMA', 'Nivel Idioma', 'Avanzado', 3, 'A',1);

	--PARENTESCO
	INSERT INTO PDTBC_PARAMETRO(N_CODPRMTRO,V_DSCRMNDOR, V_DESVALOR, N_NUMORDEN, C_ESTRGSTRO, N_VRSNTRNSC)
	VALUES(SEQ_PRMTROID.nextval,'PARENTESCO','Propio', 1, 'A',1);

	INSERT INTO PDTBC_PARAMETRO(N_CODPRMTRO,V_DSCRMNDOR, V_DESVALOR, N_NUMORDEN, C_ESTRGSTRO, N_VRSNTRNSC)
	VALUES(SEQ_PRMTROID.nextval,'PARENTESCO','Familiar', 2, 'A',1);

	INSERT INTO PDTBC_PARAMETRO(N_CODPRMTRO,V_DSCRMNDOR, V_DESVALOR, N_NUMORDEN, C_ESTRGSTRO, N_VRSNTRNSC)
	VALUES(SEQ_PRMTROID.nextval,'PARENTESCO','Amigo', 3, 'A',1);

	INSERT INTO PDTBC_PARAMETRO(N_CODPRMTRO,V_DSCRMNDOR, V_DESVALOR, N_NUMORDEN, C_ESTRGSTRO, N_VRSNTRNSC)
	VALUES(SEQ_PRMTROID.nextval,'PARENTESCO','Compañero de trabajo', 4, 'A',1);

	--Parametros
	INSERT INTO PDTBC_PARAMETRO(N_CODPRMTRO,V_DSCRMNDOR, V_NOMBRE, V_DESCRPCN, V_DESVALOR, N_NUMORDEN, C_ESTRGSTRO, N_VRSNTRNSC)
	VALUES(SEQ_PRMTROID.nextval,'PARAMETRO','ARCHIVO_TAMANO_MAXIMO', 'Tamaño máximo del archivo a cargar en MB', '2', 1, 'A',1);

	INSERT INTO PDTBC_PARAMETRO(N_CODPRMTRO,V_DSCRMNDOR, V_NOMBRE, V_DESCRPCN, V_DESVALOR, N_NUMORDEN, C_ESTRGSTRO, N_VRSNTRNSC)
	VALUES(SEQ_PRMTROID.nextval,'PARAMETRO','ELEMENTOS_POR_PAGINA', 'Número de elementos mostrados en una página de una tabla de datos', '15', 1, 'A',1);

	INSERT INTO PDTBC_PARAMETRO(N_CODPRMTRO,V_DSCRMNDOR, V_NOMBRE, V_DESCRPCN, V_DESVALOR, N_NUMORDEN, C_ESTRGSTRO, N_VRSNTRNSC)
	VALUES(SEQ_PRMTROID.nextval,'PARAMETRO','MAXIMO_ELEMENTOS_BUSQUEDA', 'Número de resultados de un listado o búsqueda', '50', 1, 'A',1);

	INSERT INTO PDTBC_PARAMETRO(N_CODPRMTRO,V_DSCRMNDOR, V_NOMBRE, V_DESCRPCN, V_DESVALOR, N_NUMORDEN, C_ESTRGSTRO, N_VRSNTRNSC)
	VALUES(SEQ_PRMTROID.nextval,'PARAMETRO','CARPETA_FOTOS', 'Carpeta que almacena los archivos de fotografía de los postulantes', 'C:\SILNETFILES\fotos\', 1, 'A',1);

	INSERT INTO PDTBC_PARAMETRO(N_CODPRMTRO,V_DSCRMNDOR, V_NOMBRE, V_DESCRPCN, V_DESVALOR, N_NUMORDEN, C_ESTRGSTRO, N_VRSNTRNSC)
	VALUES(SEQ_PRMTROID.nextval,'PARAMETRO','CARPETA_CV', 'Carpeta que almacena los archivos de fotografía de los postulantes', 'C:\SILNETFILES\cv\', 1, 'A',1);

	INSERT INTO PDTBC_PARAMETRO(N_CODPRMTRO,V_DSCRMNDOR, V_NOMBRE, V_DESCRPCN, V_DESVALOR, N_NUMORDEN, C_ESTRGSTRO, N_VRSNTRNSC)
	VALUES(SEQ_PRMTROID.nextval,'PARAMETRO','ESTILO_CAMPO_REQUERIDO', 'Estilo de los campos obligatorios', 'border-color: #A59D9D;border-width: 1px;border-style: solid;background-color: #F8F6F1;background-image: url(/);', 1, 'A',1);

	INSERT INTO PDTBC_EMPRESA(N_CODEMPRSA, V_RUCEMP, V_NOMBREEMP, V_RZNSOCIAL) VALUES (SEQ_EMPRSAID.nextval, '12345678910', 'Mi empresa', 'Mi empresa');


  
  --TIPO REFERENCIA
	INSERT INTO PDTBC_TPORFRNCIA(N_CODTPORFR,V_DSCRPCON,C_ESTRGSTRO) VALUES(SEQ_TPORFRNCAID.nextval,'Laboral','A');
	INSERT INTO PDTBC_TPORFRNCIA(N_CODTPORFR,V_DSCRPCON,C_ESTRGSTRO) VALUES(SEQ_TPORFRNCAID.nextval,'Profesional','A');
	INSERT INTO PDTBC_TPORFRNCIA(N_CODTPORFR,V_DSCRPCON,C_ESTRGSTRO) VALUES(SEQ_TPORFRNCAID.nextval,'Personal','A');
  
  
  -----  Area 
	INSERT INTO PDTBC_AREALBRAL(N_CODAREA,V_DSCRPCON)VALUES(SEQ_ARAID.NEXTVAL,'FINANZAS');
	INSERT INTO PDTBC_AREALBRAL(N_CODAREA,V_DSCRPCON)VALUES(SEQ_ARAID.NEXTVAL,'COMERCIAL');
	INSERT INTO PDTBC_AREALBRAL(N_CODAREA,V_DSCRPCON)VALUES(SEQ_ARAID.NEXTVAL,'ADMINISTRACIÓN');
	INSERT INTO PDTBC_AREALBRAL(N_CODAREA,V_DSCRPCON)VALUES(SEQ_ARAID.NEXTVAL,'PLANTA');
	INSERT INTO PDTBC_AREALBRAL(N_CODAREA,V_DSCRPCON)VALUES(SEQ_ARAID.NEXTVAL,'PRODUCCIÓN');
	INSERT INTO PDTBC_AREALBRAL(N_CODAREA,V_DSCRPCON)VALUES(SEQ_ARAID.NEXTVAL,'RECURSOS HUMANOS');
	INSERT INTO PDTBC_AREALBRAL(N_CODAREA,V_DSCRPCON)VALUES(SEQ_ARAID.NEXTVAL,'VENTAS');
	INSERT INTO PDTBC_AREALBRAL(N_CODAREA,V_DSCRPCON)VALUES(SEQ_ARAID.NEXTVAL,'GERENCIA');
	INSERT INTO PDTBC_AREALBRAL(N_CODAREA,V_DSCRPCON)VALUES(SEQ_ARAID.NEXTVAL,'DIRECCIÓN');
	INSERT INTO PDTBC_AREALBRAL(N_CODAREA,V_DSCRPCON)VALUES(SEQ_ARAID.NEXTVAL,'FABRICACIÓN');
	INSERT INTO PDTBC_AREALBRAL(N_CODAREA,V_DSCRPCON)VALUES(SEQ_ARAID.NEXTVAL,'MARKETING');
	INSERT INTO PDTBC_AREALBRAL(N_CODAREA,V_DSCRPCON)VALUES(SEQ_ARAID.NEXTVAL,'INGENIERÍA');
	INSERT INTO PDTBC_AREALBRAL(N_CODAREA,V_DSCRPCON)VALUES(SEQ_ARAID.NEXTVAL,'PROYECTOS');
	INSERT INTO PDTBC_AREALBRAL(N_CODAREA,V_DSCRPCON)VALUES(SEQ_ARAID.NEXTVAL,'PLANIFICACIÓN');
	INSERT INTO PDTBC_AREALBRAL(N_CODAREA,V_DSCRPCON)VALUES(SEQ_ARAID.NEXTVAL,'CONTABILIDAD');
	INSERT INTO PDTBC_AREALBRAL(N_CODAREA,V_DSCRPCON)VALUES(SEQ_ARAID.NEXTVAL,'COMPRAS');
	INSERT INTO PDTBC_AREALBRAL(N_CODAREA,V_DSCRPCON)VALUES(SEQ_ARAID.NEXTVAL,'ALMACÉN');
	INSERT INTO PDTBC_AREALBRAL(N_CODAREA,V_DSCRPCON)VALUES(SEQ_ARAID.NEXTVAL,'RELACIONES PÚBLICAS');
	INSERT INTO PDTBC_AREALBRAL(N_CODAREA,V_DSCRPCON)VALUES(SEQ_ARAID.NEXTVAL,'CONTROL DE CALIDAD');
	INSERT INTO PDTBC_AREALBRAL(N_CODAREA,V_DSCRPCON)VALUES(SEQ_ARAID.NEXTVAL,'MANTENIMIENTO ');
	INSERT INTO PDTBC_AREALBRAL(N_CODAREA,V_DSCRPCON)VALUES(SEQ_ARAID.NEXTVAL,'DISTRIBUCIÓN');
	INSERT INTO PDTBC_AREALBRAL(N_CODAREA,V_DSCRPCON)VALUES(SEQ_ARAID.NEXTVAL,'AUDITORÍA INTERNA');
	INSERT INTO PDTBC_AREALBRAL(N_CODAREA,V_DSCRPCON)VALUES(SEQ_ARAID.NEXTVAL,'ASISTENCIA SOCIAL');
	INSERT INTO PDTBC_AREALBRAL(N_CODAREA,V_DSCRPCON)VALUES(SEQ_ARAID.NEXTVAL,'PERSONAL');
	INSERT INTO PDTBC_AREALBRAL(N_CODAREA,V_DSCRPCON)VALUES(SEQ_ARAID.NEXTVAL,'PUBLICIDAD');
	INSERT INTO PDTBC_AREALBRAL(N_CODAREA,V_DSCRPCON)VALUES(SEQ_ARAID.NEXTVAL,'SERVICIO TÉCNICO');
	INSERT INTO PDTBC_AREALBRAL(N_CODAREA,V_DSCRPCON)VALUES(SEQ_ARAID.NEXTVAL,'TESORERÍA');
	INSERT INTO PDTBC_AREALBRAL(N_CODAREA,V_DSCRPCON)VALUES(SEQ_ARAID.NEXTVAL,'OPERACIONES');
	INSERT INTO PDTBC_AREALBRAL(N_CODAREA,V_DSCRPCON)VALUES(SEQ_ARAID.NEXTVAL,'MERCADEO');
	INSERT INTO PDTBC_AREALBRAL(N_CODAREA,V_DSCRPCON)VALUES(SEQ_ARAID.NEXTVAL,'SERVICIO Y ATENCIÓN AL CLIENTE');
  
  ---- Informativa
  INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Nacional Del Callao');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Interamericana Para El Desarrollo');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Privada San Juan Bautista');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Inca Garcilaso De La Vega');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Nacional Mayor De San Marcos - Unmsm');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Peruana De Las Americas');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Tecnologica Del Peru');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Jose Faustino Sanchez Carrion');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Alas Peruanas');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Del Pacifico');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Jaime Bausate Y Meza');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Peruana De Ciencias E Informatica');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Peruana De Investigación Y Negocios');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Femenina Del Sagrado Corazon');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Nacional Agraria La Molina');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad San Ignacio De Loyola - Usil');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Escuela Internacional De Postgrado');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Cientifica Del Sur');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Norbert Wiener');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Peruana De Integración Global');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Univ. Nacional Mayor De San Marcos (Unmsm)');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Inca Garcilaso De La Vega (Uigv)');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Peruana De Las Américas');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Tecnológica Del Perú (Utp)');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Catolica Sedes Sapientiae');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad De Ciencias Y Humanidades');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Le Cordon Bleu');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Peruana Unión');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Nacional De Educacion Enrique Guzman Y Valle');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Facultad De Teología Pontificia Y Civil De Lima');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Antonio Ruiz De Montoya');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Peruana Simón Bolivar');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Nacional De Ingenieria');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Peruana De Arte Orval');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Tecnológica De Monterrey');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad De San Andrés');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Peruana Cayetano Heredia');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Pontificia Universidad Catolica Del Peru - Pucp');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Nacional Federico Villarreal');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Privada Sergio Bernales');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad De San Martin De Porres');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Privada Arzobispo Loayza');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Esan');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad De Ciencias Y Artes De América Latina');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad De Lima');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Ricardo Palma');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Marcelino Champagnat');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Upc - Universidad Peruana De Ciencias Aplicadas');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Autónoma Del Perú');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Untecs - Universidad Nacional Tecnológica Del Cono Sur De Lima');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Nacional Toribio Rodriguez De Mendoza De Amazonas Unat');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad De Chimbote');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Los Angeles De Chimbote - Uladech');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Nacional Del Santa');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Nacional Santiago Antunez De Mayolo');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Privada San Pedro');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Privada San Pedro - Chimbote');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Nacional Jose María Arguedas');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Nacional Micaela Bastidas De Apurímac');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Tecnologica De Los Andes');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Autónoma San Francisco');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Catolica San Pablo');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Catolica Santa Maria');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Ciencias De La Salud');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Nacional De San Agustín De Arequipa - Unsa');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad De Ayacucho Federico Froebel');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Nacional De San Cristóbal De Huamanga');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Nacional De Cajamarca');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Privada Antonio Guillermo Urrelo');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Privada San Pedro - Cajamarca');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Privada Del Norte (Upnorte)');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Nacional Daniel Alcides Carrión');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Andina Del Cusco');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Nacional De San Antonio Abad Del Cusco');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Nacional De Huancavelica');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Para El Desarrollo Andino');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Continental De Ciencias E Ingeniería');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Nacional Del Centro Del Perú');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Peruana Los Andes - Upla');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Nacional Agraria De La Selva');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Nacional Hermilio Valdizan Huanuco');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Nacional San Luis Gonzaga De Ica');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Privada Abraham Valdelomar');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Privada Ada A. Byron');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Peruana Del Centro');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Privada De Huancayo');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Cesar Vallejo');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad De Negocios Y Tecnologías De Información');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Nacional De Trujillo');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Privada Antenor Orrego - Upao');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Privada De Trujillo');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Privada Del Norte');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Católica Santo Toribio De Mogrovejo');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad De Chiclayo');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad De Lambayeque');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Nacional Pedro Ruiz Gallo');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Privada Juan Mejía Baca');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Señor De Sipan');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Peruana Del Oriente');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Privada De La Selva Peruana');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad José Carlos Mariátegui');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Nacional De Moquegua');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Privada De Moquegua');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad De Piura');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Nacional De Piura');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Privada San Pedro - Piura');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Andina Nestor Caceres Velasquez');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Nacional Del Altiplano Puno');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Privada San Carlos');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Nacional Jorge Basadre Grohmann');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Privada De Tacna');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Nacional De San Martin');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Nacional De Tumbes');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Nacional Intercultural De La Amazonía');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Universidad Privada De Pucallpa');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnologico La Florida Del Inca');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto De Conservacion Y Restauracion Yachay Wasi');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnologico Publico Simon Bolivar');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Asociación Educativa Aduni');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Cesca');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Salesiano');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnologico Privado En Protesis Dental');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Asmutiomar');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Chaminade Marianistas');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Pedagogico Privado Paulo Vi');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Pedagogico Público De Educacion Especial Maria Madre');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Tomas Alva Edison');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Centro De Formación Profesional Para La Mujer Condoray');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Escuela Nacional Superior De Folklore Jose Maria Arguedas');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto De Educación Superior Teccen');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto De Educacion Superior San Martin De Chorrillos');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnologico Publico Antenor Orrego Espinoza');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Pedagogico Jose Carlos Mariategui');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Montessori');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Pedagógico Paulo Freire');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnologico Carlos Cueto Fernandini');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Asociación Educativa Santiago Antunez De Mayolo');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Ceop Benjamin Galecio Matos - Gamor');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Cesam');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Eiger - Asociacion Educativa Y C. Csc.');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Escuela Superior De Salud Sergio Bernales');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto De Artes Y Ciencias De La Comunicacion');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto De Educacion Superior Cima s');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto De Educacion Superior Paul Müller');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Pedagogico J. Chiriboga');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Peruano De La Moda');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Pestalozzi');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Pedagogico Privado Amauta');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Pedagogico Publico De Educacion Inicial');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnologico Cayetano Heredia');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnologico Latino');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnologico Privado Peruano Aleman');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnologico Publico Argentina');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnologico Taylor');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Jacqueline Instituto De Belleza');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnológico Público Huaycan');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Complejo Hospitalario San Pablo');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnico Alexander Graham Bell');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Ams Campus');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Centro De Estudios De Aviación Profesional - Avia');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Ceo De La Clinica Del Pie San Isidro');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Escuela Iberoamericana De Hotelería Y Turismo');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Escuela Latinoamericana De La Moda');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Escuela Superior Privada De Optica Y Optometria');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Grupo Idat');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Idat');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Pedagogico Privado Raul Porras Barrenechea');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Claridad');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto De Los Andes');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto San Ignacio De Loyola');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Ceop Ntra. Sra. De Guadalupe');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Capeco - Istp De La Construccion');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnologico Jose Pardo');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Centro De La Fotografia S.A.');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Conservatorio De Lima Josafat Roel Pineda');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Ensabap - Escuela Nacional Superior Autonoma De Bellas Artes Del Perú');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto De Educacion Superior Rochdale');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto De Educacion Superior Unicenter');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto De Modelos Y Misses Marina Mora');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Daniel Alcides Carrion');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Pedagógico San Marcos');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Kumon Matematicas');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Taller De Alta Cocina Y Pasteleria Gialvi');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Art Nouveau');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Asociacion Educativa Nicolas Copernico');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Cecitel');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Escuela De Comercio Exterior Montessori');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Escuela Superior De Marketing Y Publicidad');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Ihcitec');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Enrique Encinas');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Pedagogico Femenino Guillermina Encinas De Nuñez');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnológico Norbert Wiener');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Metropolitano');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Sky Master Escuela De Hoteleria Y Turismo');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Tecnicos En Telefonia Cecitel');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Wernher Von Braun');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto De Profesiones Empresariales');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnologico El Buen Pastor');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnologico Publico Ramiro Priale Priale');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Escuela De Gestion De Agronegocios');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Chio Lecca');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior De Alta Cocina D gallia');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Eurohispano');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Infap Notre Dame');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Pedagogico Maria Auxiliadora');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Istp San Marcos');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Tecnicas Americanas De Estudio');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Abaco');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'C.E.O.P. Virgen Del Carmen E.I.R.L.');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Centro Educativo Ocupacional Particular Lenny s');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Edith Sachs - Artes Visuales');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Ela');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Escuela De Bar - Mozos & Cruceros');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Escuela De Diseño Y Decoracion Interior De Miraflores');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Escuela De Podologia');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Escuela Superior De Bellas Artes Corriente Alterna');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Escuela Superior De Marketing Del Peru');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Fx Animation School');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Idea');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Ilvem');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Internacional Del Arte Y La Moda - Mod Art');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Matrix');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Peruano De Marketing');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto San Martin Del Peru');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Sise');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Ipad');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Le Cordon Bleu Peru');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Pers Academia De Nuevas Artes');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Proinne - Comercio Exterior');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Talenttus');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Andina De Turismo');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Cepea');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnologico Alessandro Volta');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnologico Elmer Faucett');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnologico Publico Naciones Unidas');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Ipae');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Atelier Siete');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'C.E.O. Juana Alarco De Dammert');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Escuela Superior De Arte Y Diseño Orval');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Escuela Superior Infoking');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto De Educacion Superior Medalla Milagrosa');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto De Textileria Y Comercio');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Sencico');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Ccaem Peru S.A.');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Centro De Altos Estudios De La Moda - Ceam');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Centro Peruano De Estudios Bancarios - Cepeban');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Charles Chaplin');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Cibermundo');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Cibertec');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Escuela De Cine De Lima');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Escuela De Estetica Integral Meche Solaeche');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Escuela Peruana De Gastronomia Y Vinos');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Esec Peru S.A.');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Frieda Holler');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Gastrotur Peru');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Hospitality Management School');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Cultural Italo Peruano');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto De Formacion Bancaria');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Peruano De Publicidad - Ipp');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Orson Welles S.A.');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnológico De Comercio Exterior Istecex - Centros Academicos De Adex (Ceadex)');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnológico Excelencia Profesional - Expro');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnologico Privado International American College');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Leo Design');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Nina Design');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Pedagogico Privado Catequetico - Ispec');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Pedagogico Solidaridad Campoy');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior San Silvestre-Master Byte');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Pedagogico Catequetico');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Nacional De Investigación Y Capacitación De Telecomunicaciones - Inictel');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior De Directores Técnicos De Fútbol');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Nuestra Señora De La Piedad');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Infotur');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnologico Luis Negreiros Vega');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Ceop Milenium');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Infes - Instituto De Formación Y Capacitación En Seguridad');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Peruano De Cheffs');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior De La Clinica Ricardo Palma');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Rural Valle Grande');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Tecsup');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Grupo Trilce');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Aeria');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'British Academy');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'C.E.O.P. San Antonio Maria Claret');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Ceop Maria Auxiliadora');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Ceop San Antonio María Claret');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Esit Escuela De Interpretación Y Traducción De Lima');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Pedagogico Nacional Monterrico');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Pedagogico Privado Nuestra Señora De La Reconciliacion');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Pedagogico San Francisco De Asis Monterrico');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnologico De Enfermeria Madre Josefina Vannini');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Sales Force International');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'San Ignacio De Monterrico');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Escuela Monte Catini');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior San Vicente De Paul');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnologico Oscar Diaz Bravo');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'C.F.T. Promae');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Pedagogico Publico Manuel Gonzalez Prada');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Pedagogico Luis Baudin');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnologico Publico Juan Velasco Alvarado');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnologico Publico Villa Maria');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Pedagógico Público Yauyos');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnologico Cenfotes');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Alianza Francesa');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Centro Cultural Peruano Norteamericano');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Centro De Estudios Turísticos Elmer Faucett');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Centro De Idiomas Atelier');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Cepea - Arequipa');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Eci');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Essam Instituto Superior');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Futurekids Computación Para Niños');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Grupo Esade');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Ingles Sistema Asdi');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Agrario Del Sur');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto De Educacion Superior Thomas Jefferson');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Del Sur');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Maria Montessori');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior De Enfermeria Salud Y Belleza');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Ipsidata');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Pedagogico Privado Jean Piaget');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Pedagógico Público Arequipa');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Pedagógico San Fernando Del Valle Aqp');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Pedagógico Santa María');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior San Jose Oriol');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnológico J. Prado');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Thomas Jefferson');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Sencico - Arequipa');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Tecsup - Arequipa');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Telesup');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior De Turismo Josafat Roel Pineda');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Pedagógico Público Nuestra Señora De Lourdes');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnológico Privado La Pontificia');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnológico Público Cutervo');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnológico República De Alemania');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Bitec');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Asociacion Pukllasunchis');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Ceop Virgen Del Tránsito');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto De Educacion Superior Americana Del Cusco');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto De Educación Superior Didaskalio Cristo Rey');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto De Educacion Superior Luis Pasteur');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Pedagógico Privado Arco Iris Cusco');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Pedagógico Privado San Ignacio De Loyola Del Cusco');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnológico Privado Khipu');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Matrix');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnológico Continental');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnológico Agropecuario Huando');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto De Educación Superior Cesar Vallejo');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto De Educación Superior Peruano-Canadiense');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Infonet');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto De Educación Superior Santa Lucía');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Pedagogico Privado Selva Central');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Pedagogico Público Teodoro Peñaloza');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnologico Eugenio Paccelly');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Inverandina S.R.Ltda.');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Ispp Juan Pablo Ii Concepcion');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Istp Andres Avelino Caceres Dorregaray');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Americana De Turismo');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Ceop San Peter Systems');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'I.S.P.P. David Sánchez Infante');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto De Educación Superior Tecnológica Y Pedagógica Cima');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Leonardo Da Vinci');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Pedagogico Oxford');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Pedagogico Privado Juan Pablo Ii');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Pedagógico Virgen De La Puerta');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnologico Pablo Casals');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Tecnologico Del Norte');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Sencico - Trujillo');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'American Institute');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto De Ciencias Empresariales Y Liderazgo Republica Argentina');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto De Educacion Superior Particular Peru - Francia');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Isa Chiclayo');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Pedagógico Inca Garcilaso De La Vega');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Pedagogico Privado El Pacifico');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Pedagogico Privado Peruano Canadiense');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnologico El Pacifico');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Senati - Chiclayo');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Sencico - Chiclayo');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Apeplac - Apoyo Psicopedagogico Especializado En Problemas De Lenguaje Aprendizaje Y Conducta');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Centro De Formacion En Turismo - Cenfotur');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Educa Online');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Global Institute');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituo De Estudios Previsionales');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto De Enseñanza Superior Columbia');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnologico Publico Diseño');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnológico Público Arturo Sabroso Montoya');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Isp Divino Niño');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Seminario Evangelico Peruano');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Senati');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Toulouse Lautrec');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Escuela Superior De Música Lorenzo Luján Darjón');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto De Educacion Superior Reyna De Las Americas');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Pedagogico Privado San Juan De Iquitos');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Pedagogico Publico Edislao Mera Davila');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Pedagógico Público Loreto');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnologico Pedro A. Del Aguila Hidalgo');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'O.N.G. Educativa Eiger');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnológico Estatal José Carlos Mariátegui');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnologico Luis E. Valcarcel');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnológico Público Alexander Von Humboldt');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Escuela Superior De Arte Ignacio Merino');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto De Educacion Superior Abaco');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto De Educacion Superior Alas Peruanas');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Pedagógico Privado Vicente Sánchez Valer');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnologico Alas Peruanas');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnologico Almirante Miguel Grau');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Pedagógico Público De Juliaca');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Pedagógico Puno');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnológico Nazaret');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnologico Privado De Turismo San Luis De Alba');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnológico Y De Investigación No Estatal Del Altiplano');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto De Educación Superior Tokio');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto De Educacion Superior Guillermo Almenara Martins');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto De Educación Superior John Von Neumann');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto De Educación Superior Tecnológico Sistemas Del Sur');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Pedagogico Jose Jimenez Borja');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnologico Francisco De Paula Gonzalez Vigil');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Instituto Superior Tecnológico San Luis María De Montfort');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Centro De Educacion Ocupacional Privado Juan Pablo Ii');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Modern Systems');
	INSERT INTO PDTBC_INSTFORMTIVA(N_CODINTFTV,V_DSCRPCON) VALUES(SEQ_INSTTCONFRMTVAID.nextval,'Senati - Pucallpa');

--Estado formacion
	INSERT INTO PDTBC_ESTADO(N_CODESTDO,V_DSCRMNDOR, V_DSCRPCON)
	VALUES(SEQ_ESTDOID.nextval,'ESTADO_FORMACION', 'Concluido');

	INSERT INTO PDTBC_ESTADO(N_CODESTDO,V_DSCRMNDOR, V_DSCRPCON)
	VALUES(SEQ_ESTDOID.nextval,'ESTADO_FORMACION', 'No Concluido');

	INSERT INTO PDTBC_ESTADO(N_CODESTDO,V_DSCRMNDOR, V_DSCRPCON)
	VALUES(SEQ_ESTDOID.nextval,'ESTADO_FORMACION', 'En curso');



	commit;
  --rollback;