package pe.gob.trabajo.pcd.modelo.dominio;

// Generated 27/01/2011 05:11:53 PM by Hibernate Tools 3.4.0.Beta1


/**
 * TiprmParametro generated by hbm2java
 */
public class Configuracion extends BeanEntidadGenericoAutogenerado implements java.io.Serializable {
	
	private static final long serialVersionUID = 1291279995582441766L;
	
	private String discriminador;
	private Long versionTransaccion;
	private String nemonico;
	private String nombre;
	private String valor;
	private Integer orden;
	private String nivel;
	private String tipoAcceso;
	
	public String getDiscriminador() {
		return discriminador;
	}
	public void setDiscriminador(String discriminador) {
		this.discriminador = discriminador;
	}
	public Long getVersionTransaccion() {
		return versionTransaccion;
	}
	public void setVersionTransaccion(Long versionTransaccion) {
		this.versionTransaccion = versionTransaccion;
	}
	public String getNemonico() {
		return nemonico;
	}
	public void setNemonico(String nemonico) {
		this.nemonico = nemonico;
	}
	public String getNombre() {
		return nombre;
	}
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	public String getValor() {
		return valor;
	}
	public void setValor(String valor) {
		this.valor = valor;
	}
	public Integer getOrden() {
		return orden;
	}
	public void setOrden(Integer orden) {
		this.orden = orden;
	}
	public String getNivel() {
		return nivel;
	}
	public void setNivel(String nivel) {
		this.nivel = nivel;
	}
	public String getTipoAcceso() {
		return tipoAcceso;
	}
	public void setTipoAcceso(String tipoAcceso) {
		this.tipoAcceso = tipoAcceso;
	}
	
}
