package pe.gob.trabajo.pcd.modelo.dominio;

// Generated 27/01/2011 05:11:53 PM by Hibernate Tools 3.4.0.Beta1


/**
 * TiprmArea generated by hbm2java
 */
public class Area extends BeanEntidadGenericoAutogenerado implements java.io.Serializable {
	
	private static final long serialVersionUID = 4752788667166986205L;

}
