package pe.gob.trabajo.pcd.modelo.dominio;

import java.util.ArrayList;
import java.util.List;

/**
 * TiprmTipoEstablecimiento generated by hbm2java
 */
public class TipoEstablecimiento extends BeanEntidadGenericoAutogenerado implements java.io.Serializable {

	private static final long serialVersionUID = 7429597555950609024L;
	
	private List<TipoEstablecimiento> tipoEstablecimiento = new ArrayList<TipoEstablecimiento>();

	public List<TipoEstablecimiento> getTipoEstablecimiento() {
		return tipoEstablecimiento;
	}

	public void setTipoEstablecimiento(List<TipoEstablecimiento> tipoEstablecimiento) {
		this.tipoEstablecimiento = tipoEstablecimiento;
	}
	public List<TipoEstablecimiento> getValoresTipoEstablecimiento() {
		ArrayList<TipoEstablecimiento> lista = new ArrayList<TipoEstablecimiento>();

		for (TipoEstablecimiento tipoEstablecimientos : tipoEstablecimiento) {
			if (tipoEstablecimientos != null) {
				lista.add(tipoEstablecimientos);
			}
		}
		return lista;
	}

}
