package pe.gob.trabajo.pcd.modelo.dominio;

// Generated 27/01/2011 05:11:53 PM by Hibernate Tools 3.4.0.Beta1

/**
 * TiprmRol generated by hbm2java
 */
public class Rol extends BeanEntidadGenericoAutogenerado implements java.io.Serializable {

	private static final long serialVersionUID = -373336017633847499L;

	public Rol() {

	}

	public Rol(Long id) {
		setId(id);
	}

}
