package pe.gob.trabajo.pcd.modelo.dominio;

import java.util.ArrayList;
import java.util.List;

/**
 * TiprmTipoEmpresa generated by hbm2java
 */
public class TipoEmpresa extends BeanEntidadGenericoAutogenerado implements java.io.Serializable {
	
	private static final long serialVersionUID = -1915087668185298766L;
	
	private List<TipoEmpresa> tipoEmpresa = new ArrayList<TipoEmpresa>();

	public List<TipoEmpresa> getTipoEmpresa() {
		return tipoEmpresa;
	}

	public void setTipoEmpresa(List<TipoEmpresa> tipoEmpresa) {
		this.tipoEmpresa = tipoEmpresa;
	}
	public List<TipoEmpresa> getValoresTipoEmpresa() {
		ArrayList<TipoEmpresa> lista = new ArrayList<TipoEmpresa>();

		for (TipoEmpresa tipoEmpresas : tipoEmpresa) {
			if (tipoEmpresas != null) {
				lista.add(tipoEmpresas);
			}
		}
		return lista;
	}

}
