package pe.gob.trabajo.pcd.modelo.dominio;

// Generated 28/01/2011 10:09:44 AM by Hibernate Tools 3.4.0.Beta1

import java.util.ArrayList;
import java.util.List;

/**
 * TiprmEspecialidadProfesional generated by hbm2java
 */
public class EspecialidadProfesional extends BeanEntidadGenericoAutogenerado implements java.io.Serializable {
	
	private static final long serialVersionUID = -8154833707952171133L;
	
	private Integer principal;
	
	private List<RelacionTecnologia> relacionEspecialidadDestino = new ArrayList<RelacionTecnologia>();
	private List<RelacionTecnologia> relacionEspecialidadOrigen = new ArrayList<RelacionTecnologia>();
	
	public List<RelacionTecnologia> getRelacionEspecialidadDestino() {
		return relacionEspecialidadDestino;
	}
	public void setRelacionEspecialidadDestino(
			List<RelacionTecnologia> relacionEspecialidadDestino) {
		this.relacionEspecialidadDestino = relacionEspecialidadDestino;
	}
	public List<RelacionTecnologia> getRelacionEspecialidadOrigen() {
		return relacionEspecialidadOrigen;
	}
	public void setRelacionEspecialidadOrigen(
			List<RelacionTecnologia> relacionEspecialidadOrigen) {
		this.relacionEspecialidadOrigen = relacionEspecialidadOrigen;
	}
	/**
	 * @return the principal
	 */
	public Integer getPrincipal() {
		return principal;
	}
	/**
	 * @param principal the principal to set
	 */
	public void setPrincipal(Integer principal) {
		this.principal = principal;
	}
	
	public Boolean getOcupacionPrincipal () {
		boolean retorno = false;
		
		if ( principal!=null && principal.equals(1)) {
			retorno = true;
		}
		return retorno;
	}
	
	public void setOcupacionPrincipal(Boolean idiomaNativo) {
		if (idiomaNativo) {
			this.principal = 1;
		} else {
			this.principal = 0;
		}
	}
}
