package pe.gob.trabajo.pcd.modelo.dominio;

// Generated 27/01/2011 05:11:53 PM by Hibernate Tools 3.4.0.Beta1

/**
 * TiprfPrfsnalReferencia generated by hbm2java
 */
public class Referencia extends BeanEntidadGenericoAutogeneradoValidable implements
		java.io.Serializable {

	private static final long serialVersionUID = -9080300609097164275L;

	private Puesto puesto;
	private Empresa empresa;
	private Persona persona;
	private TipoReferencia tipoReferencia;
	private Profesional profesional;
	private String nombreReferenciaDestino;
	private String telefonoPrincipal;
	private String telefonoSecundario;
	private String email;
	private String comentario;
	
	private String cargo;
	private String descripcionCargo;

	public Puesto getPuesto() {
		return puesto;
	}

	public void setPuesto(Puesto puesto) {
		this.puesto = puesto;
	}
	
	public Empresa getEmpresa() {
		return empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	public Persona getPersona() {
		return persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	public TipoReferencia getTipoReferencia() {
		return tipoReferencia;
	}

	public void setTipoReferencia(TipoReferencia tipoReferencia) {
		this.tipoReferencia = tipoReferencia;
	}

	public Profesional getProfesional() {
		return profesional;
	}

	public void setProfesional(Profesional profesional) {
		this.profesional = profesional;
	}

	public String getNombreReferenciaDestino() {
		return nombreReferenciaDestino;
	}

	public void setNombreReferenciaDestino(String nombreReferenciaDestino) {
		this.nombreReferenciaDestino = nombreReferenciaDestino;
	}

	public String getTelefonoPrincipal() {
		return telefonoPrincipal;
	}

	public void setTelefonoPrincipal(String telefonoPrincipal) {
		this.telefonoPrincipal = telefonoPrincipal;
	}

	public String getTelefonoSecundario() {
		return telefonoSecundario;
	}

	public void setTelefonoSecundario(String telefonoSecundario) {
		this.telefonoSecundario = telefonoSecundario;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getComentario() {
		return comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	public String getCargo() {
		return cargo;
	}

	public void setCargo(String cargo) {
		this.cargo = cargo;
	}

	public String getDescripcionCargo() {
		return descripcionCargo;
	}

	public void setDescripcionCargo(String descripcionCargo) {
		this.descripcionCargo = descripcionCargo;
	}

}
