package pe.gob.trabajo.pcd.modelo.dominio;

// Generated 27/01/2011 05:11:53 PM by Hibernate Tools 3.4.0.Beta1


/**
 * TiprmEstado generated by hbm2java
 */
public class Estado extends BeanEntidadGenericoAutogenerado implements java.io.Serializable {
	
	private static final long serialVersionUID = -605285273951839968L;
	
	private String discriminador;

	public String getDiscriminador() {
		return discriminador;
	}

	public void setDiscriminador(String discriminador) {
		this.discriminador = discriminador;
	}
	
}
