package pe.gob.trabajo.pcd.modelo.dominio;


/**
 * PersonaDiscapacidad generated by hbm2java
 */
public class PersonaInteresesOcupacionales extends BeanEntidadGenericoAutogenerado
		implements java.io.Serializable {

	private static final long serialVersionUID = -3680170806367541576L;
	
	private Persona persona;
	private String otrosIntereses;
	private String preferenciasLaborales;
	
	private Boolean aireLibre1;
	private Boolean aireLibre2;
	private Boolean aireLibre3;
	private Boolean aireLibre4;
	private Boolean aireLibre5;
	private Boolean aireLibre6;
	private Boolean aireLibre7;
	private Boolean aireLibre8;
	
	private Boolean tecnicoManual1;
	private Boolean tecnicoManual2;
	private Boolean tecnicoManual3;
	private Boolean tecnicoManual4;
	private Boolean tecnicoManual5;
	private Boolean tecnicoManual6;
	
	private Boolean cientificoAbstractas1;
	private Boolean cientificoAbstractas2;
	private Boolean cientificoAbstractas3;
	private Boolean cientificoAbstractas4;
	private Boolean cientificoAbstractas5;
	private Boolean cientificoAbstractas6;
	
	private Boolean sociales1;
	private Boolean sociales2;
	private Boolean sociales3;
	private Boolean sociales4;
	private Boolean sociales5;
	private Boolean sociales6;
	private Boolean sociales7;
	private Boolean sociales8;
	
	private Boolean comerciales1;
	private Boolean comerciales2;
	private Boolean comerciales3;
	private Boolean comerciales4;
	private Boolean comerciales5;
	private Boolean comerciales6;
	private Boolean comerciales7;
	private Boolean comerciales8;
	private Boolean comerciales9;
	
	private Boolean musicales1;
	private Boolean musicales2;
	private Boolean musicales3;
	private Boolean musicales4;
	
	private Boolean artisticas1;
	private Boolean artisticas2;
	private Boolean artisticas3;
	private Boolean artisticas4;
	private Boolean artisticas5;
	private Boolean artisticas6;
	private Boolean artisticas7;
	private Boolean artisticas8;
	
	private Boolean ocio1;
	private Boolean ocio2;
	private Boolean ocio3;
	private Boolean ocio4;
	private Boolean ocio5;
	private Boolean ocio6;
	/**
	 * @return the persona
	 */
	public Persona getPersona() {
		return persona;
	}
	/**
	 * @param persona the persona to set
	 */
	public void setPersona(Persona persona) {
		this.persona = persona;
	}
	/**
	 * @return the otrosIntereses
	 */
	public String getOtrosIntereses() {
		return otrosIntereses;
	}
	/**
	 * @param otrosIntereses the otrosIntereses to set
	 */
	public void setOtrosIntereses(String otrosIntereses) {
		this.otrosIntereses = otrosIntereses;
	}
	/**
	 * @return the preferenciasLaborales
	 */
	public String getPreferenciasLaborales() {
		return preferenciasLaborales;
	}
	/**
	 * @param preferenciasLaborales the preferenciasLaborales to set
	 */
	public void setPreferenciasLaborales(String preferenciasLaborales) {
		this.preferenciasLaborales = preferenciasLaborales;
	}
	/**
	 * @return the aireLibre1
	 */
	public Boolean getAireLibre1() {
		return aireLibre1;
	}
	/**
	 * @param aireLibre1 the aireLibre1 to set
	 */
	public void setAireLibre1(Boolean aireLibre1) {
		this.aireLibre1 = aireLibre1;
	}
	/**
	 * @return the aireLibre2
	 */
	public Boolean getAireLibre2() {
		return aireLibre2;
	}
	/**
	 * @param aireLibre2 the aireLibre2 to set
	 */
	public void setAireLibre2(Boolean aireLibre2) {
		this.aireLibre2 = aireLibre2;
	}
	/**
	 * @return the aireLibre3
	 */
	public Boolean getAireLibre3() {
		return aireLibre3;
	}
	/**
	 * @param aireLibre3 the aireLibre3 to set
	 */
	public void setAireLibre3(Boolean aireLibre3) {
		this.aireLibre3 = aireLibre3;
	}
	/**
	 * @return the aireLibre4
	 */
	public Boolean getAireLibre4() {
		return aireLibre4;
	}
	/**
	 * @param aireLibre4 the aireLibre4 to set
	 */
	public void setAireLibre4(Boolean aireLibre4) {
		this.aireLibre4 = aireLibre4;
	}
	/**
	 * @return the aireLibre5
	 */
	public Boolean getAireLibre5() {
		return aireLibre5;
	}
	/**
	 * @param aireLibre5 the aireLibre5 to set
	 */
	public void setAireLibre5(Boolean aireLibre5) {
		this.aireLibre5 = aireLibre5;
	}
	/**
	 * @return the aireLibre6
	 */
	public Boolean getAireLibre6() {
		return aireLibre6;
	}
	/**
	 * @param aireLibre6 the aireLibre6 to set
	 */
	public void setAireLibre6(Boolean aireLibre6) {
		this.aireLibre6 = aireLibre6;
	}
	/**
	 * @return the aireLibre7
	 */
	public Boolean getAireLibre7() {
		return aireLibre7;
	}
	/**
	 * @param aireLibre7 the aireLibre7 to set
	 */
	public void setAireLibre7(Boolean aireLibre7) {
		this.aireLibre7 = aireLibre7;
	}
	/**
	 * @return the aireLibre8
	 */
	public Boolean getAireLibre8() {
		return aireLibre8;
	}
	/**
	 * @param aireLibre8 the aireLibre8 to set
	 */
	public void setAireLibre8(Boolean aireLibre8) {
		this.aireLibre8 = aireLibre8;
	}
	/**
	 * @return the tecnicoManual1
	 */
	public Boolean getTecnicoManual1() {
		return tecnicoManual1;
	}
	/**
	 * @param tecnicoManual1 the tecnicoManual1 to set
	 */
	public void setTecnicoManual1(Boolean tecnicoManual1) {
		this.tecnicoManual1 = tecnicoManual1;
	}
	/**
	 * @return the tecnicoManual2
	 */
	public Boolean getTecnicoManual2() {
		return tecnicoManual2;
	}
	/**
	 * @param tecnicoManual2 the tecnicoManual2 to set
	 */
	public void setTecnicoManual2(Boolean tecnicoManual2) {
		this.tecnicoManual2 = tecnicoManual2;
	}
	/**
	 * @return the tecnicoManual3
	 */
	public Boolean getTecnicoManual3() {
		return tecnicoManual3;
	}
	/**
	 * @param tecnicoManual3 the tecnicoManual3 to set
	 */
	public void setTecnicoManual3(Boolean tecnicoManual3) {
		this.tecnicoManual3 = tecnicoManual3;
	}
	/**
	 * @return the tecnicoManual4
	 */
	public Boolean getTecnicoManual4() {
		return tecnicoManual4;
	}
	/**
	 * @param tecnicoManual4 the tecnicoManual4 to set
	 */
	public void setTecnicoManual4(Boolean tecnicoManual4) {
		this.tecnicoManual4 = tecnicoManual4;
	}
	/**
	 * @return the tecnicoManual5
	 */
	public Boolean getTecnicoManual5() {
		return tecnicoManual5;
	}
	/**
	 * @param tecnicoManual5 the tecnicoManual5 to set
	 */
	public void setTecnicoManual5(Boolean tecnicoManual5) {
		this.tecnicoManual5 = tecnicoManual5;
	}
	/**
	 * @return the tecnicoManual6
	 */
	public Boolean getTecnicoManual6() {
		return tecnicoManual6;
	}
	/**
	 * @param tecnicoManual6 the tecnicoManual6 to set
	 */
	public void setTecnicoManual6(Boolean tecnicoManual6) {
		this.tecnicoManual6 = tecnicoManual6;
	}
	/**
	 * @return the cientificoAbstractas1
	 */
	public Boolean getCientificoAbstractas1() {
		return cientificoAbstractas1;
	}
	/**
	 * @param cientificoAbstractas1 the cientificoAbstractas1 to set
	 */
	public void setCientificoAbstractas1(Boolean cientificoAbstractas1) {
		this.cientificoAbstractas1 = cientificoAbstractas1;
	}
	/**
	 * @return the cientificoAbstractas2
	 */
	public Boolean getCientificoAbstractas2() {
		return cientificoAbstractas2;
	}
	/**
	 * @param cientificoAbstractas2 the cientificoAbstractas2 to set
	 */
	public void setCientificoAbstractas2(Boolean cientificoAbstractas2) {
		this.cientificoAbstractas2 = cientificoAbstractas2;
	}
	/**
	 * @return the cientificoAbstractas3
	 */
	public Boolean getCientificoAbstractas3() {
		return cientificoAbstractas3;
	}
	/**
	 * @param cientificoAbstractas3 the cientificoAbstractas3 to set
	 */
	public void setCientificoAbstractas3(Boolean cientificoAbstractas3) {
		this.cientificoAbstractas3 = cientificoAbstractas3;
	}
	/**
	 * @return the cientificoAbstractas4
	 */
	public Boolean getCientificoAbstractas4() {
		return cientificoAbstractas4;
	}
	/**
	 * @param cientificoAbstractas4 the cientificoAbstractas4 to set
	 */
	public void setCientificoAbstractas4(Boolean cientificoAbstractas4) {
		this.cientificoAbstractas4 = cientificoAbstractas4;
	}
	/**
	 * @return the cientificoAbstractas5
	 */
	public Boolean getCientificoAbstractas5() {
		return cientificoAbstractas5;
	}
	/**
	 * @param cientificoAbstractas5 the cientificoAbstractas5 to set
	 */
	public void setCientificoAbstractas5(Boolean cientificoAbstractas5) {
		this.cientificoAbstractas5 = cientificoAbstractas5;
	}
	/**
	 * @return the cientificoAbstractas6
	 */
	public Boolean getCientificoAbstractas6() {
		return cientificoAbstractas6;
	}
	/**
	 * @param cientificoAbstractas6 the cientificoAbstractas6 to set
	 */
	public void setCientificoAbstractas6(Boolean cientificoAbstractas6) {
		this.cientificoAbstractas6 = cientificoAbstractas6;
	}
	/**
	 * @return the sociales1
	 */
	public Boolean getSociales1() {
		return sociales1;
	}
	/**
	 * @param sociales1 the sociales1 to set
	 */
	public void setSociales1(Boolean sociales1) {
		this.sociales1 = sociales1;
	}
	/**
	 * @return the sociales2
	 */
	public Boolean getSociales2() {
		return sociales2;
	}
	/**
	 * @param sociales2 the sociales2 to set
	 */
	public void setSociales2(Boolean sociales2) {
		this.sociales2 = sociales2;
	}
	/**
	 * @return the sociales3
	 */
	public Boolean getSociales3() {
		return sociales3;
	}
	/**
	 * @param sociales3 the sociales3 to set
	 */
	public void setSociales3(Boolean sociales3) {
		this.sociales3 = sociales3;
	}
	/**
	 * @return the sociales4
	 */
	public Boolean getSociales4() {
		return sociales4;
	}
	/**
	 * @param sociales4 the sociales4 to set
	 */
	public void setSociales4(Boolean sociales4) {
		this.sociales4 = sociales4;
	}
	/**
	 * @return the sociales5
	 */
	public Boolean getSociales5() {
		return sociales5;
	}
	/**
	 * @param sociales5 the sociales5 to set
	 */
	public void setSociales5(Boolean sociales5) {
		this.sociales5 = sociales5;
	}
	/**
	 * @return the sociales6
	 */
	public Boolean getSociales6() {
		return sociales6;
	}
	/**
	 * @param sociales6 the sociales6 to set
	 */
	public void setSociales6(Boolean sociales6) {
		this.sociales6 = sociales6;
	}
	/**
	 * @return the sociales7
	 */
	public Boolean getSociales7() {
		return sociales7;
	}
	/**
	 * @param sociales7 the sociales7 to set
	 */
	public void setSociales7(Boolean sociales7) {
		this.sociales7 = sociales7;
	}
	/**
	 * @return the sociales8
	 */
	public Boolean getSociales8() {
		return sociales8;
	}
	/**
	 * @param sociales8 the sociales8 to set
	 */
	public void setSociales8(Boolean sociales8) {
		this.sociales8 = sociales8;
	}
	/**
	 * @return the comerciales1
	 */
	public Boolean getComerciales1() {
		return comerciales1;
	}
	/**
	 * @param comerciales1 the comerciales1 to set
	 */
	public void setComerciales1(Boolean comerciales1) {
		this.comerciales1 = comerciales1;
	}
	/**
	 * @return the comerciales2
	 */
	public Boolean getComerciales2() {
		return comerciales2;
	}
	/**
	 * @param comerciales2 the comerciales2 to set
	 */
	public void setComerciales2(Boolean comerciales2) {
		this.comerciales2 = comerciales2;
	}
	/**
	 * @return the comerciales3
	 */
	public Boolean getComerciales3() {
		return comerciales3;
	}
	/**
	 * @param comerciales3 the comerciales3 to set
	 */
	public void setComerciales3(Boolean comerciales3) {
		this.comerciales3 = comerciales3;
	}
	/**
	 * @return the comerciales4
	 */
	public Boolean getComerciales4() {
		return comerciales4;
	}
	/**
	 * @param comerciales4 the comerciales4 to set
	 */
	public void setComerciales4(Boolean comerciales4) {
		this.comerciales4 = comerciales4;
	}
	/**
	 * @return the comerciales5
	 */
	public Boolean getComerciales5() {
		return comerciales5;
	}
	/**
	 * @param comerciales5 the comerciales5 to set
	 */
	public void setComerciales5(Boolean comerciales5) {
		this.comerciales5 = comerciales5;
	}
	/**
	 * @return the comerciales6
	 */
	public Boolean getComerciales6() {
		return comerciales6;
	}
	/**
	 * @param comerciales6 the comerciales6 to set
	 */
	public void setComerciales6(Boolean comerciales6) {
		this.comerciales6 = comerciales6;
	}
	/**
	 * @return the comerciales7
	 */
	public Boolean getComerciales7() {
		return comerciales7;
	}
	/**
	 * @param comerciales7 the comerciales7 to set
	 */
	public void setComerciales7(Boolean comerciales7) {
		this.comerciales7 = comerciales7;
	}
	/**
	 * @return the comerciales8
	 */
	public Boolean getComerciales8() {
		return comerciales8;
	}
	/**
	 * @param comerciales8 the comerciales8 to set
	 */
	public void setComerciales8(Boolean comerciales8) {
		this.comerciales8 = comerciales8;
	}
	/**
	 * @return the comerciales9
	 */
	public Boolean getComerciales9() {
		return comerciales9;
	}
	/**
	 * @param comerciales9 the comerciales9 to set
	 */
	public void setComerciales9(Boolean comerciales9) {
		this.comerciales9 = comerciales9;
	}
	/**
	 * @return the musicales1
	 */
	public Boolean getMusicales1() {
		return musicales1;
	}
	/**
	 * @param musicales1 the musicales1 to set
	 */
	public void setMusicales1(Boolean musicales1) {
		this.musicales1 = musicales1;
	}
	/**
	 * @return the musicales2
	 */
	public Boolean getMusicales2() {
		return musicales2;
	}
	/**
	 * @param musicales2 the musicales2 to set
	 */
	public void setMusicales2(Boolean musicales2) {
		this.musicales2 = musicales2;
	}
	/**
	 * @return the musicales3
	 */
	public Boolean getMusicales3() {
		return musicales3;
	}
	/**
	 * @param musicales3 the musicales3 to set
	 */
	public void setMusicales3(Boolean musicales3) {
		this.musicales3 = musicales3;
	}
	/**
	 * @return the musicales4
	 */
	public Boolean getMusicales4() {
		return musicales4;
	}
	/**
	 * @param musicales4 the musicales4 to set
	 */
	public void setMusicales4(Boolean musicales4) {
		this.musicales4 = musicales4;
	}
	/**
	 * @return the artisticas1
	 */
	public Boolean getArtisticas1() {
		return artisticas1;
	}
	/**
	 * @param artisticas1 the artisticas1 to set
	 */
	public void setArtisticas1(Boolean artisticas1) {
		this.artisticas1 = artisticas1;
	}
	/**
	 * @return the artisticas2
	 */
	public Boolean getArtisticas2() {
		return artisticas2;
	}
	/**
	 * @param artisticas2 the artisticas2 to set
	 */
	public void setArtisticas2(Boolean artisticas2) {
		this.artisticas2 = artisticas2;
	}
	/**
	 * @return the artisticas3
	 */
	public Boolean getArtisticas3() {
		return artisticas3;
	}
	/**
	 * @param artisticas3 the artisticas3 to set
	 */
	public void setArtisticas3(Boolean artisticas3) {
		this.artisticas3 = artisticas3;
	}
	/**
	 * @return the artisticas4
	 */
	public Boolean getArtisticas4() {
		return artisticas4;
	}
	/**
	 * @param artisticas4 the artisticas4 to set
	 */
	public void setArtisticas4(Boolean artisticas4) {
		this.artisticas4 = artisticas4;
	}
	/**
	 * @return the artisticas5
	 */
	public Boolean getArtisticas5() {
		return artisticas5;
	}
	/**
	 * @param artisticas5 the artisticas5 to set
	 */
	public void setArtisticas5(Boolean artisticas5) {
		this.artisticas5 = artisticas5;
	}
	/**
	 * @return the artisticas6
	 */
	public Boolean getArtisticas6() {
		return artisticas6;
	}
	/**
	 * @param artisticas6 the artisticas6 to set
	 */
	public void setArtisticas6(Boolean artisticas6) {
		this.artisticas6 = artisticas6;
	}
	/**
	 * @return the artisticas7
	 */
	public Boolean getArtisticas7() {
		return artisticas7;
	}
	/**
	 * @param artisticas7 the artisticas7 to set
	 */
	public void setArtisticas7(Boolean artisticas7) {
		this.artisticas7 = artisticas7;
	}
	/**
	 * @return the artisticas8
	 */
	public Boolean getArtisticas8() {
		return artisticas8;
	}
	/**
	 * @param artisticas8 the artisticas8 to set
	 */
	public void setArtisticas8(Boolean artisticas8) {
		this.artisticas8 = artisticas8;
	}
	/**
	 * @return the ocio1
	 */
	public Boolean getOcio1() {
		return ocio1;
	}
	/**
	 * @param ocio1 the ocio1 to set
	 */
	public void setOcio1(Boolean ocio1) {
		this.ocio1 = ocio1;
	}
	/**
	 * @return the ocio2
	 */
	public Boolean getOcio2() {
		return ocio2;
	}
	/**
	 * @param ocio2 the ocio2 to set
	 */
	public void setOcio2(Boolean ocio2) {
		this.ocio2 = ocio2;
	}
	/**
	 * @return the ocio3
	 */
	public Boolean getOcio3() {
		return ocio3;
	}
	/**
	 * @param ocio3 the ocio3 to set
	 */
	public void setOcio3(Boolean ocio3) {
		this.ocio3 = ocio3;
	}
	/**
	 * @return the ocio4
	 */
	public Boolean getOcio4() {
		return ocio4;
	}
	/**
	 * @param ocio4 the ocio4 to set
	 */
	public void setOcio4(Boolean ocio4) {
		this.ocio4 = ocio4;
	}
	/**
	 * @return the ocio5
	 */
	public Boolean getOcio5() {
		return ocio5;
	}
	/**
	 * @param ocio5 the ocio5 to set
	 */
	public void setOcio5(Boolean ocio5) {
		this.ocio5 = ocio5;
	}
	/**
	 * @return the ocio6
	 */
	public Boolean getOcio6() {
		return ocio6;
	}
	/**
	 * @param ocio6 the ocio6 to set
	 */
	public void setOcio6(Boolean ocio6) {
		this.ocio6 = ocio6;
	}
	
}
