package pe.gob.trabajo.pcd.modelo.dominio;

// Generated 27/01/2011 05:11:53 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;

/**
 * TiprfPrfsnalFormacion generated by hbm2java
 */
public class Capacitacion extends BeanEntidadGenericoAutogeneradoValidable implements java.io.Serializable {

	private static final long serialVersionUID = -6941861850266575953L;

	private Profesional profesional;

	private Integer tipoCapacitacion; // camm

	private String nombCapacitacion;// si
	private Integer duracion; // camm
	private Integer tipoDuracion;// camm
	private Date fechaCapacitacion;// camm

	public Profesional getProfesional() {
		return profesional;
	}

	public void setProfesional(Profesional profesional) {
		this.profesional = profesional;
	}

	public Integer getTipoCapacitacion() {
		return tipoCapacitacion;
	}

	public void setTipoCapacitacion(Integer tipoCapacitacion) {
		this.tipoCapacitacion = tipoCapacitacion;
	}

	public String getNombCapacitacion() {
		return nombCapacitacion;
	}

	public void setNombCapacitacion(String nombCapacitacion) {
		this.nombCapacitacion = nombCapacitacion;
	}

	public Integer getDuracion() {
		return duracion;
	}

	public void setDuracion(Integer duracion) {
		this.duracion = duracion;
	}

	public Integer getTipoDuracion() {
		return tipoDuracion;
	}

	public void setTipoDuracion(Integer tipoDuracion) {
		this.tipoDuracion = tipoDuracion;
	}

	public Date getFechaCapacitacion() {
		return fechaCapacitacion;
	}

	public void setFechaCapacitacion(Date fechaCapacitacion) {
		this.fechaCapacitacion = fechaCapacitacion;
	}

}
