package pe.gob.trabajo.pcd.modelo.dominio;

/**
 * TiprfPrfsnalFormacion generated by hbm2java
 */
public class Conocimiento extends BeanEntidadGenericoAutogeneradoValidable implements java.io.Serializable {

	private static final long serialVersionUID = -6941861850266575953L;

	private Profesional profesional;

	private Integer tipoConocimiento; // camm
	private Integer tipoIdioma;
	
	private Idioma idioma;

	private String nombConocimiento;// si
	private Integer nivelConocimiento; // camm
	
	

	public Profesional getProfesional() {
		return profesional;
	}

	public void setProfesional(Profesional profesional) {
		this.profesional = profesional;
	}

	public Integer getTipoConocimiento() {
		return tipoConocimiento;
	}

	public void setTipoConocimiento(Integer tipoConocimiento) {
		this.tipoConocimiento = tipoConocimiento;
	}

	public String getNombConocimiento() {
		return nombConocimiento;
	}

	public void setNombConocimiento(String nombConocimiento) {
		this.nombConocimiento = nombConocimiento;
	}

	public Integer getNivelConocimiento() {
		return nivelConocimiento;
	}

	public void setNivelConocimiento(Integer nivelConocimiento) {
		this.nivelConocimiento = nivelConocimiento;
	}

	public Integer getTipoIdioma() {
		return tipoIdioma;
	}

	public void setTipoIdioma(Integer tipoIdioma) {
		this.tipoIdioma = tipoIdioma;
	}

	public Idioma getIdioma() {
		return idioma;
	}

	public void setIdioma(Idioma idioma) {
		this.idioma = idioma;
	}

	
	

}
