package pe.gob.trabajo.pcd.modelo.dominio;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

// Generated 27/01/2011 05:11:53 PM by Hibernate Tools 3.4.0.Beta1


/**
 * TiprmPersonaContacto generated by hbm2java
 */
public class Contacto extends BeanEntidadGenericoAutogeneradoValidable implements java.io.Serializable {
	
	private static final long serialVersionUID = 2969125835494364503L;
	
	private Persona persona;
	private Long idPersonaDestino;
	private String nombreContacto;
	private Integer parentesco;
	private String comentario;
	private Set<ContactoMedio> contactoMedios = new HashSet<ContactoMedio>();
	
	private ContactoMedio contactoMedio = new ContactoMedio();
	
	public ContactoMedio getContactoMedio() {
		return contactoMedio;
	}
	public void setContactoMedio(ContactoMedio contactoMedio) {
		this.contactoMedio = contactoMedio;
	}
	public Persona getPersona() {
		return persona;
	}
	public void setPersona(Persona persona) {
		this.persona = persona;
	}
	public Long getIdPersonaDestino() {
		return idPersonaDestino;
	}
	public void setIdPersonaDestino(Long idPersonaDestino) {
		this.idPersonaDestino = idPersonaDestino;
	}
	public String getNombreContacto() {
		return nombreContacto;
	}
	public void setNombreContacto(String nombreContacto) {
		this.nombreContacto = nombreContacto;
	}
	public Integer getParentesco() {
		return parentesco;
	}
	public void setParentesco(Integer parentesco) {
		this.parentesco = parentesco;
	}
	public String getComentario() {
		return comentario;
	}
	public void setComentario(String comentario) {
		this.comentario = comentario;
	}
	public Set<ContactoMedio> getContactoMedios() {
		return contactoMedios;
	}
	public void setContactoMedios(Set<ContactoMedio> contactoMedios) {
		this.contactoMedios = contactoMedios;
	}
	public List<ContactoMedio> getValoresContacto() {
		ArrayList<ContactoMedio> lista = new ArrayList<ContactoMedio>();

		for (ContactoMedio contactoMedio : contactoMedios) {
			if (contactoMedio != null) {
				lista.add(contactoMedio);
			}
		}
		return lista;
	}
	
	public List<Contacto> getDatosContacto() {
		ArrayList<Contacto> lista = new ArrayList<Contacto>();
		for (Contacto contacto : lista) {
			if (contacto != null) {
				lista.add(contacto);
			}
		}
		return lista;
	}
	public List<Contacto> getPersonasContacto() {
		ArrayList<Contacto> lista = new ArrayList<Contacto>();
		
		for (Contacto contacto : lista) {
			if (contacto != null) {
				lista.add(contacto);
			}
		}
		return lista;
	}
	public List<Contacto> getPersonasContactos(){
		ArrayList<Contacto> lista = new ArrayList<Contacto>();
		for(Contacto contacto : lista){
			if(contacto !=null && !getId().equals(contacto.getIdPersonaDestino())){
				lista.add(contacto);
			}
		}
		return lista;
	}
	

}
