package pe.gob.trabajo.pcd.modelo.dominio;


// Generated 27/01/2011 05:11:53 PM by Hibernate Tools 3.4.0.Beta1


/**
 * TiprmEmpresa generated by hbm2java
 */
public class Empresa extends BeanEntidadGenericoAutogenerado implements java.io.Serializable {
	
	private static final long serialVersionUID = -4864173715519354683L;
	
	private String ruc;
	private String nombreComercial;
	private String razonSocial;
	private String empresaMatriz; //campo para mapear con las empresas de SIMINTRA
	private String direccion; 
	private Long   tipoEmpresa; //regimen privada, publica etc
	private String ciiu;
	private String ciiuDescripcion;
	private String personaContacto;	
	private Long numEmpleados;
	private Usuario usuario;
	
	
	public static Empresa construirEmpresa(EmpresaSunat e) {
		Empresa bean = new Empresa();
		bean.setId(0L);
		bean.setRuc(e.getRuc());
		bean.setNombreComercial(e.getNombreComercial());
		bean.setRazonSocial(e.getRazonSocial());
		bean.setCiiu(e.getCiiu());
		return bean;
	}


	public String getRuc() {
		return ruc;
	}


	public void setRuc(String ruc) {
		this.ruc = ruc;
	}


	public String getNombreComercial() {
		return nombreComercial;
	}


	public void setNombreComercial(String nombreComercial) {
		this.nombreComercial = nombreComercial;
	}


	public String getRazonSocial() {
		return razonSocial;
	}


	public void setRazonSocial(String razonSocial) {
		this.razonSocial = razonSocial;
	}


	public String getEmpresaMatriz() {
		return empresaMatriz;
	}


	public void setEmpresaMatriz(String empresaMatriz) {
		this.empresaMatriz = empresaMatriz;
	}


	public Long getTipoEmpresa() {
		return tipoEmpresa;
	}


	public void setTipoEmpresa(Long tipoEmpresa) {
		this.tipoEmpresa = tipoEmpresa;
	}


	public String getCiiu() {
		return ciiu;
	}


	public void setCiiu(String ciiu) {
		this.ciiu = ciiu;
	}


	public String getCiiuDescripcion() {
		return ciiuDescripcion;
	}


	public void setCiiuDescripcion(String ciiuDescripcion) {
		this.ciiuDescripcion = ciiuDescripcion;
	}


	public String getPersonaContacto() {
		return personaContacto;
	}


	public void setPersonaContacto(String personaContacto) {
		this.personaContacto = personaContacto;
	}


	public Long getNumEmpleados() {
		return numEmpleados;
	}


	public void setNumEmpleados(Long numEmpleados) {
		this.numEmpleados = numEmpleados;
	}


	public Usuario getUsuario() {
		return usuario;
	}


	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}


	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}


	public String getDireccion() {
		return direccion;
	}

	

}
