package pe.gob.trabajo.pcd.modelo.dominio;

// Generated 27/01/2011 05:11:53 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;

/**
 * TiprfPrfsnalExprncaLbral generated by hbm2java
 */
public class ExperienciaLaboral extends BeanEntidadGenericoAutogeneradoValidable implements java.io.Serializable {
	
	private static final long serialVersionUID = -4214949705600541604L;
	
	private Empresa empresa;
//	private RolLaboral rolLaboral;
	private Area area;
	private Profesional profesional;
//	private Puesto puesto;
//	private Sector sector;
	private Date inicio;
	private Date termino;
	private String rubro;
	private Integer pais;
	private String ciudad;
	private String actividades;
	private String logros;
	private String jefe;
	private String telefono;
	private String motivoCese;
	private Double sueldo;
	
	private String cargo;
	private String descripcionCargo;
	
	private String institucion;
	private Integer horas;
	
	private String idOcupacion;
	private String descripcionOcupacion;
	
	private Long idSector;
	private String descripcionSector;
	
	private Integer principal;
	
//	private Long idUsroValidador;
//	private Date fechaValidacion;
//	private Character validado;
	
	private String actividadEconomica;//camm
	private String actividades2; //camm
	
	public Empresa getEmpresa() {
		return empresa;
	}
	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}
//	public RolLaboral getRolLaboral() {
//		return rolLaboral;
//	}
//	public void setRolLaboral(RolLaboral rolLaboral) {
//		this.rolLaboral = rolLaboral;
//	}
	public Area getArea() {
		return area;
	}
	public void setArea(Area area) {
		this.area = area;
	}
	public Profesional getProfesional() {
		return profesional;
	}
	public void setProfesional(Profesional profesional) {
		this.profesional = profesional;
	}
//	public Puesto getPuesto() {
//		return puesto;
//	}
//	public void setPuesto(Puesto puesto) {
//		this.puesto = puesto;
//	}
//	public Sector getSector() {
//		return sector;
//	}
//	public void setSector(Sector sector) {
//		this.sector = sector;
//	}
	public Date getInicio() {
		return inicio;
	}
	public void setInicio(Date inicio) {
		this.inicio = inicio;
	}
	public Date getTermino() {
		return termino;
	}
	public void setTermino(Date termino) {
		this.termino = termino;
	}
	
	public String getRubro() {
		return rubro;
	}
	public void setRubro(String rubro) {
		this.rubro = rubro;
	}
	public Integer getPais() {
		return pais;
	}
	public void setPais(Integer pais) {
		this.pais = pais;
	}
	public String getCiudad() {
		return ciudad;
	}
	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}
	public String getActividades() {
		return actividades;
	}
	public void setActividades(String actividades) {
		this.actividades = actividades;
	}
	public String getLogros() {
		return logros;
	}
	public void setLogros(String logros) {
		this.logros = logros;
	}
	public String getJefe() {
		return jefe;
	}
	public void setJefe(String jefe) {
		this.jefe = jefe;
	}
	public String getTelefono() {
		return telefono;
	}
	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}
	public String getMotivoCese() {
		return motivoCese;
	}
	public void setMotivoCese(String motivoCese) {
		this.motivoCese = motivoCese;
	}
	public Double getSueldo() {
		return sueldo;
	}
	public void setSueldo(Double sueldo) {
		this.sueldo = sueldo;
	}
	public String getCargo() {
		return cargo;
	}
	public void setCargo(String cargo) {
		this.cargo = cargo;
	}
	public String getDescripcionCargo() {
		return descripcionCargo;
	}
	public void setDescripcionCargo(String descripcionCargo) {
		this.descripcionCargo = descripcionCargo;
	}
	
	public String getInstitucion() {
		return institucion;
	}
	public void setInstitucion(String institucion) {
		this.institucion = institucion;
	}
	public Integer getHoras() {
		return horas;
	}
	public void setHoras(Integer horas) {
		this.horas = horas;
	}
	public Long getIdSector() {
		return idSector;
	}
	public void setIdSector(Long idSector) {
		this.idSector = idSector;
	}
	public String getIdOcupacion() {
		return idOcupacion;
	}
	public void setIdOcupacion(String idOcupacion) {
		this.idOcupacion = idOcupacion;
	}
	public String getDescripcionOcupacion() {
		return descripcionOcupacion;
	}
	public void setDescripcionOcupacion(String descripcionOcupacion) {
		this.descripcionOcupacion = descripcionOcupacion;
	}
	public String getDescripcionSector() {
		return descripcionSector;
	}
	public void setDescripcionSector(String descripcionSector) {
		this.descripcionSector = descripcionSector;
	}
	public Integer getPrincipal() {
		return principal;
	}
	public void setPrincipal(Integer principal) {
		this.principal = principal;
	}
	
	public Boolean getEmpleoPrincipal () {
		boolean retorno = false;
		
		if ( principal!=null && principal.equals(1)) {
			retorno = true;
		}
		return retorno;
	}
	
	public void setEmpleoPrincipal(Boolean idiomaNativo) {
		if (idiomaNativo) {
			this.principal = 1;
		} else {
			this.principal = 0;
		}
	}
	public String getActividadEconomica() {
		return actividadEconomica;
	}
	public void setActividadEconomica(String actividadEconomica) {
		this.actividadEconomica = actividadEconomica;
	}
	public String getActividades2() {
		return actividades2;
	}
	public void setActividades2(String actividades2) {
		this.actividades2 = actividades2;
	}
	
	
		
}
