package pe.gob.trabajo.pcd.modelo.dominio;

// Generated 27/01/2011 05:11:53 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;

/**
 * TiprfPrfsnalFormacion generated by hbm2java
 */
public class Formacion extends BeanEntidadGenericoAutogeneradoValidable implements java.io.Serializable {

	private static final long serialVersionUID = -6941861850266575953L;

	private TipoFormacion tipoFormacion;
	private Profesional profesional;
	private Estado estado;
	private InstitucionFormativa institucionFormativa;// SI
	private String campoEstudio;
	private Date inicio;
	private Date termino;
	private Integer duracion;
	private Integer unidad;
	private String ciudad;
	private String idNivel;
	private String descripcionNivel;
	private NivelFormacion nivelFormativo;// SI

	private String idProfesion;
	private String descripcionProfesion;// si
	private String idGrupoProfesion;
	private String descripcionGrupoProfesion;

	private String detalleFormacion;

	private Integer gradoEstudio; // camm
	private Integer ultimoEstudio;// camm
	private Integer ultimoNivelEstudio;// camm
	private String  descripcionCarrera;// si

	public TipoFormacion getTipoFormacion() {
		return tipoFormacion;
	}

	public void setTipoFormacion(TipoFormacion tipoFormacion) {
		this.tipoFormacion = tipoFormacion;
	}

	public Profesional getProfesional() {
		return profesional;
	}

	public void setProfesional(Profesional profesional) {
		this.profesional = profesional;
	}

	public Estado getEstado() {
		return estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}

	public InstitucionFormativa getInstitucionFormativa() {
		return institucionFormativa;
	}

	public void setInstitucionFormativa(InstitucionFormativa institucionFormativa) {
		this.institucionFormativa = institucionFormativa;
	}

	public String getCampoEstudio() {
		return campoEstudio;
	}

	public void setCampoEstudio(String campoEstudio) {
		this.campoEstudio = campoEstudio;
	}

	public Date getInicio() {
		return inicio;
	}

	public void setInicio(Date inicio) {
		this.inicio = inicio;
	}

	public Date getTermino() {
		return termino;
	}

	public void setTermino(Date termino) {
		this.termino = termino;
	}

	public Integer getDuracion() {
		return duracion;
	}

	public void setDuracion(Integer duracion) {
		this.duracion = duracion;
	}

	public Integer getUnidad() {
		return unidad;
	}

	public void setUnidad(Integer unidad) {
		this.unidad = unidad;
	}

	public String getCiudad() {
		return ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	public String getIdNivel() {
		return idNivel;
	}

	public void setIdNivel(String idNivel) {
		this.idNivel = idNivel;
	}

	public String getDescripcionNivel() {
		return descripcionNivel;
	}

	public void setDescripcionNivel(String descripcionNivel) {
		this.descripcionNivel = descripcionNivel;
	}

	public NivelFormacion getNivelFormativo() {
		return nivelFormativo;
	}

	public void setNivelFormativo(NivelFormacion nivelFormativo) {
		this.nivelFormativo = nivelFormativo;
	}

	public String getIdProfesion() {
		return idProfesion;
	}

	public void setIdProfesion(String idProfesion) {
		this.idProfesion = idProfesion;
	}

	public String getDescripcionProfesion() {
		return descripcionProfesion;
	}

	public void setDescripcionProfesion(String descripcionProfesion) {
		this.descripcionProfesion = descripcionProfesion;
	}

	public String getIdGrupoProfesion() {
		return idGrupoProfesion;
	}

	public void setIdGrupoProfesion(String idGrupoProfesion) {
		this.idGrupoProfesion = idGrupoProfesion;
	}

	public String getDescripcionGrupoProfesion() {
		return descripcionGrupoProfesion;
	}

	public void setDescripcionGrupoProfesion(String descripcionGrupoProfesion) {
		this.descripcionGrupoProfesion = descripcionGrupoProfesion;
	}

	public String getDetalleFormacion() {
		return detalleFormacion;
	}

	public void setDetalleFormacion(String detalleFormacion) {
		this.detalleFormacion = detalleFormacion;
	}

	public Integer getGradoEstudio() {
		return gradoEstudio;
	}

	public void setGradoEstudio(Integer gradoEstudio) {
		this.gradoEstudio = gradoEstudio;
	}

	public Integer getUltimoEstudio() {
		return ultimoEstudio;
	}

	public void setUltimoEstudio(Integer ultimoEstudio) {
		this.ultimoEstudio = ultimoEstudio;
	}

	public Integer getUltimoNivelEstudio() {
		return ultimoNivelEstudio;
	}

	public void setUltimoNivelEstudio(Integer ultimoNivelEstudio) {
		this.ultimoNivelEstudio = ultimoNivelEstudio;
	}

	public String getDescripcionCarrera() {
		return descripcionCarrera;
	}

	public void setDescripcionCarrera(String descripcionCarrera) {
		this.descripcionCarrera = descripcionCarrera;
	}

}
