package pe.gob.trabajo.pcd.modelo.dominio;

import java.util.Date;

/**
 * TiprmPersona generated by hbm2java
 */
public class Pedido extends BeanEntidadGenericoAutogenerado implements
		java.io.Serializable {

	private static final long serialVersionUID = 6620639202423186067L;
	private Date fechaRegistro;
	private Date fechaCierre;
	private Empresa empleador;

	private String nombre;
	private Integer nroPuestosCubrir; // add by Hever
	private Integer nroCandidatosEnviar; // add by Hever

	private String nombreContacto; // add by Hever
	private String puestoContacto; // add by Hever
	private String telefContacto; // add by Hever
	private String anexoContacto; // add by Hever
	private String correoContacto; // add by Hever

	private Date fechaIniEntrevista; // add by Hever
	private Date fechaFinEntrevista; // add by Hever
	private String horarioEntrevista; // add by Hever
	private String lugarEntrevista; // add by Hever

	private Integer codTipoRemuneracion; // add by Hever
	private Integer movilidad; // add by Hever
	private Integer refrigerio; // add by Hever
	private Integer bonificacion; // add by Hever
	private Integer seguro; // add by Hever
	private Integer comisiones; // add by Hever

	private Integer codTipoPuesto; // add by Hever

	private Integer personalACargo;
	private Integer numPersonalACargo;
	private String tareas;
	private Integer jornada;
	private Double remuneracion;
	private String horario;
	private String departamento;
	private String provincia;
	private String distrito;
	// private String direccion;
	private String nombreLugarResidencia;

	// Datos complementarios add by Hever
	private Integer codEstudiosFormales;
	private String profesion;
	private Integer codGrado;
	private Integer licenciaConducir; // 0: NO 1:SI
	private String categoriaLicenciaConducir;
	private Integer vehiculoPropio; // 0: NO 1:SI
	private Integer sexoPreferente;
	private Integer edadIni;
	private Integer edadFin;
	private Integer experienciaRequerida;
	private Integer codTipoExperiencia;
	private Integer codTipoDiscapacidad;
	private Integer habilidad1;
	private Integer habilidad2;
	private Integer habilidad3;
	private Integer habilidad4;
	private Integer habilidad5;
	private Integer habilidad6;
	private Integer habilidad7;
	private Integer habilidad8;
	private Integer habilidad9;
	private Integer habilidad10;
	private Integer habilidad11;
	private Integer habilidad12a;
	private Integer habilidad12b;
	private Integer habilidad12c;
	private Integer habilidad12d;
	private Integer habilidad13;
	private Integer habilidad14a;
	private Integer habilidad14b;
	private Integer habilidad15;
	private Integer habilidad16;
	private Integer habilidad17;
	private Integer habilidad18;
	private Integer habilidad19;
	private Integer habilidad20;
	private Integer habilidad21;
	private Integer habilidad22;
	private Integer habilidad23;
	private Integer habilidad24;
	private Integer habilidad25;

	// Datos adicionales
	private Integer contratoPcdActual; // 0: NO 1:SI
	private Integer contratoPcdAntes; // 0: NO 1:SI
	private Integer instalacionAdecuada; // 0: NO 1:SI
	private String barreras;
	private Integer nroSuperiores;
	private Integer nroCompaneros;
	private Integer nroSubordinados;
	private String descCompaneros;
	private String descMoviliario;
	private String descTecnologia;
	private String descHerramientas;
	private String descMaquinarias;
	private String descVehiculos;
	private String descOtros;

	private String descEntornoAmbiental;
	private String descFactoresRiesgo;
	private String descProyAjustes;

	private Integer cuotaEmpleo; // 0: NO 1:SI
	private String motivoContratoOtros;

	public Pedido() {
		super();
	}

	public Date getFechaRegistro() {
		return fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	public Date getFechaCierre() {
		return fechaCierre;
	}

	public void setFechaCierre(Date fechaCierre) {
		this.fechaCierre = fechaCierre;
	}

	public Empresa getEmpleador() {
		return empleador;
	}

	public void setEmpleador(Empresa empleador) {
		this.empleador = empleador;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Integer getNroPuestosCubrir() {
		return nroPuestosCubrir;
	}

	public void setNroPuestosCubrir(Integer nroPuestosCubrir) {
		this.nroPuestosCubrir = nroPuestosCubrir;
	}

	public Integer getNroCandidatosEnviar() {
		return nroCandidatosEnviar;
	}

	public void setNroCandidatosEnviar(Integer nroCandidatosEnviar) {
		this.nroCandidatosEnviar = nroCandidatosEnviar;
	}

	public String getNombreContacto() {
		return nombreContacto;
	}

	public void setNombreContacto(String nombreContacto) {
		this.nombreContacto = nombreContacto;
	}

	public String getPuestoContacto() {
		return puestoContacto;
	}

	public void setPuestoContacto(String puestoContacto) {
		this.puestoContacto = puestoContacto;
	}

	public String getTelefContacto() {
		return telefContacto;
	}

	public void setTelefContacto(String telefContacto) {
		this.telefContacto = telefContacto;
	}

	public String getAnexoContacto() {
		return anexoContacto;
	}

	public void setAnexoContacto(String anexoContacto) {
		this.anexoContacto = anexoContacto;
	}

	public String getCorreoContacto() {
		return correoContacto;
	}

	public void setCorreoContacto(String correoContacto) {
		this.correoContacto = correoContacto;
	}

	public Date getFechaIniEntrevista() {
		return fechaIniEntrevista;
	}

	public void setFechaIniEntrevista(Date fechaIniEntrevista) {
		this.fechaIniEntrevista = fechaIniEntrevista;
	}

	public Date getFechaFinEntrevista() {
		return fechaFinEntrevista;
	}

	public void setFechaFinEntrevista(Date fechaFinEntrevista) {
		this.fechaFinEntrevista = fechaFinEntrevista;
	}

	public String getHorarioEntrevista() {
		return horarioEntrevista;
	}

	public void setHorarioEntrevista(String horarioEntrevista) {
		this.horarioEntrevista = horarioEntrevista;
	}

	public String getLugarEntrevista() {
		return lugarEntrevista;
	}

	public void setLugarEntrevista(String lugarEntrevista) {
		this.lugarEntrevista = lugarEntrevista;
	}

	public Integer getCodTipoRemuneracion() {
		return codTipoRemuneracion;
	}

	public void setCodTipoRemuneracion(Integer codTipoRemuneracion) {
		this.codTipoRemuneracion = codTipoRemuneracion;
	}

	public Integer getMovilidad() {
		return movilidad;
	}

	public void setMovilidad(Integer movilidad) {
		this.movilidad = movilidad;
	}

	public Integer getRefrigerio() {
		return refrigerio;
	}

	public void setRefrigerio(Integer refrigerio) {
		this.refrigerio = refrigerio;
	}

	public Integer getBonificacion() {
		return bonificacion;
	}

	public void setBonificacion(Integer bonificacion) {
		this.bonificacion = bonificacion;
	}

	public Integer getSeguro() {
		return seguro;
	}

	public void setSeguro(Integer seguro) {
		this.seguro = seguro;
	}

	public Integer getComisiones() {
		return comisiones;
	}

	public void setComisiones(Integer comisiones) {
		this.comisiones = comisiones;
	}

	public Integer getCodTipoPuesto() {
		return codTipoPuesto;
	}

	public void setCodTipoPuesto(Integer codTipoPuesto) {
		this.codTipoPuesto = codTipoPuesto;
	}

	public Integer getCodEstudiosFormales() {
		return codEstudiosFormales;
	}

	public void setCodEstudiosFormales(Integer codEstudiosFormales) {
		this.codEstudiosFormales = codEstudiosFormales;
	}

	public String getProfesion() {
		return profesion;
	}

	public void setProfesion(String profesion) {
		this.profesion = profesion;
	}

	public Integer getCodGrado() {
		return codGrado;
	}

	public void setCodGrado(Integer codGrado) {
		this.codGrado = codGrado;
	}

	public Integer getLicenciaConducir() {
		return licenciaConducir;
	}

	public void setLicenciaConducir(Integer licenciaConducir) {
		this.licenciaConducir = licenciaConducir;
	}

	public String getCategoriaLicenciaConducir() {
		return categoriaLicenciaConducir;
	}

	public void setCategoriaLicenciaConducir(String categoriaLicenciaConducir) {
		this.categoriaLicenciaConducir = categoriaLicenciaConducir;
	}

	public Integer getVehiculoPropio() {
		return vehiculoPropio;
	}

	public void setVehiculoPropio(Integer vehiculoPropio) {
		this.vehiculoPropio = vehiculoPropio;
	}

	public Integer getSexoPreferente() {
		return sexoPreferente;
	}

	public void setSexoPreferente(Integer sexoPreferente) {
		this.sexoPreferente = sexoPreferente;
	}

	public Integer getEdadIni() {
		return edadIni;
	}

	public void setEdadIni(Integer edadIni) {
		this.edadIni = edadIni;
	}

	public Integer getEdadFin() {
		return edadFin;
	}

	public void setEdadFin(Integer edadFin) {
		this.edadFin = edadFin;
	}

	public Integer getExperienciaRequerida() {
		return experienciaRequerida;
	}

	public void setExperienciaRequerida(Integer experienciaRequerida) {
		this.experienciaRequerida = experienciaRequerida;
	}

	public Integer getCodTipoExperiencia() {
		return codTipoExperiencia;
	}

	public void setCodTipoExperiencia(Integer codTipoExperiencia) {
		this.codTipoExperiencia = codTipoExperiencia;
	}

	public Integer getCodTipoDiscapacidad() {
		return codTipoDiscapacidad;
	}

	public void setCodTipoDiscapacidad(Integer codTipoDiscapacidad) {
		this.codTipoDiscapacidad = codTipoDiscapacidad;
	}

	public Integer getHabilidad1() {
		return habilidad1;
	}

	public void setHabilidad1(Integer habilidad1) {
		this.habilidad1 = habilidad1;
	}

	public Integer getHabilidad2() {
		return habilidad2;
	}

	public void setHabilidad2(Integer habilidad2) {
		this.habilidad2 = habilidad2;
	}

	public Integer getHabilidad3() {
		return habilidad3;
	}

	public void setHabilidad3(Integer habilidad3) {
		this.habilidad3 = habilidad3;
	}

	public Integer getHabilidad4() {
		return habilidad4;
	}

	public void setHabilidad4(Integer habilidad4) {
		this.habilidad4 = habilidad4;
	}

	public Integer getHabilidad5() {
		return habilidad5;
	}

	public void setHabilidad5(Integer habilidad5) {
		this.habilidad5 = habilidad5;
	}

	public Integer getHabilidad6() {
		return habilidad6;
	}

	public void setHabilidad6(Integer habilidad6) {
		this.habilidad6 = habilidad6;
	}

	public Integer getHabilidad7() {
		return habilidad7;
	}

	public void setHabilidad7(Integer habilidad7) {
		this.habilidad7 = habilidad7;
	}

	public Integer getHabilidad8() {
		return habilidad8;
	}

	public void setHabilidad8(Integer habilidad8) {
		this.habilidad8 = habilidad8;
	}

	public Integer getHabilidad9() {
		return habilidad9;
	}

	public void setHabilidad9(Integer habilidad9) {
		this.habilidad9 = habilidad9;
	}

	public Integer getHabilidad10() {
		return habilidad10;
	}

	public void setHabilidad10(Integer habilidad10) {
		this.habilidad10 = habilidad10;
	}

	public Integer getHabilidad11() {
		return habilidad11;
	}

	public void setHabilidad11(Integer habilidad11) {
		this.habilidad11 = habilidad11;
	}

	public Integer getHabilidad12a() {
		return habilidad12a;
	}

	public void setHabilidad12a(Integer habilidad12a) {
		this.habilidad12a = habilidad12a;
	}

	public Integer getHabilidad12b() {
		return habilidad12b;
	}

	public void setHabilidad12b(Integer habilidad12b) {
		this.habilidad12b = habilidad12b;
	}

	public Integer getHabilidad12c() {
		return habilidad12c;
	}

	public void setHabilidad12c(Integer habilidad12c) {
		this.habilidad12c = habilidad12c;
	}

	public Integer getHabilidad12d() {
		return habilidad12d;
	}

	public void setHabilidad12d(Integer habilidad12d) {
		this.habilidad12d = habilidad12d;
	}

	public Integer getHabilidad13() {
		return habilidad13;
	}

	public void setHabilidad13(Integer habilidad13) {
		this.habilidad13 = habilidad13;
	}

	public Integer getHabilidad14a() {
		return habilidad14a;
	}

	public void setHabilidad14a(Integer habilidad14a) {
		this.habilidad14a = habilidad14a;
	}

	public Integer getHabilidad14b() {
		return habilidad14b;
	}

	public void setHabilidad14b(Integer habilidad14b) {
		this.habilidad14b = habilidad14b;
	}

	public Integer getHabilidad15() {
		return habilidad15;
	}

	public void setHabilidad15(Integer habilidad15) {
		this.habilidad15 = habilidad15;
	}

	public Integer getHabilidad16() {
		return habilidad16;
	}

	public void setHabilidad16(Integer habilidad16) {
		this.habilidad16 = habilidad16;
	}

	public Integer getHabilidad17() {
		return habilidad17;
	}

	public void setHabilidad17(Integer habilidad17) {
		this.habilidad17 = habilidad17;
	}

	public Integer getHabilidad18() {
		return habilidad18;
	}

	public void setHabilidad18(Integer habilidad18) {
		this.habilidad18 = habilidad18;
	}

	public Integer getHabilidad19() {
		return habilidad19;
	}

	public void setHabilidad19(Integer habilidad19) {
		this.habilidad19 = habilidad19;
	}

	public Integer getHabilidad20() {
		return habilidad20;
	}

	public void setHabilidad20(Integer habilidad20) {
		this.habilidad20 = habilidad20;
	}

	public Integer getHabilidad21() {
		return habilidad21;
	}

	public void setHabilidad21(Integer habilidad21) {
		this.habilidad21 = habilidad21;
	}

	public Integer getHabilidad22() {
		return habilidad22;
	}

	public void setHabilidad22(Integer habilidad22) {
		this.habilidad22 = habilidad22;
	}

	public Integer getHabilidad23() {
		return habilidad23;
	}

	public void setHabilidad23(Integer habilidad23) {
		this.habilidad23 = habilidad23;
	}

	public Integer getHabilidad24() {
		return habilidad24;
	}

	public void setHabilidad24(Integer habilidad24) {
		this.habilidad24 = habilidad24;
	}

	public Integer getHabilidad25() {
		return habilidad25;
	}

	public void setHabilidad25(Integer habilidad25) {
		this.habilidad25 = habilidad25;
	}

	public Integer getPersonalACargo() {
		return personalACargo;
	}

	public void setPersonalACargo(Integer personalACargo) {
		this.personalACargo = personalACargo;
	}

	public Integer getNumPersonalACargo() {
		return numPersonalACargo;
	}

	public void setNumPersonalACargo(Integer numPersonalACargo) {
		this.numPersonalACargo = numPersonalACargo;
	}

	public Double getRemuneracion() {
		return remuneracion;
	}

	public void setRemuneracion(Double remuneracion) {
		this.remuneracion = remuneracion;
	}

	public String getHorario() {
		return horario;
	}

	public void setHorario(String horario) {
		this.horario = horario;
	}

	public String getDepartamento() {
		return departamento;
	}

	public void setDepartamento(String departamento) {
		this.departamento = departamento;
	}

	public String getProvincia() {
		return provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	public String getDistrito() {
		return distrito;
	}

	public void setDistrito(String distrito) {
		this.distrito = distrito;
	}

	public String getNombreLugarResidencia() {
		return nombreLugarResidencia;
	}

	public void setNombreLugarResidencia(String nombreLugarResidencia) {
		this.nombreLugarResidencia = nombreLugarResidencia;
	}

	public Integer getJornada() {
		return jornada;
	}

	public void setJornada(Integer jornada) {
		this.jornada = jornada;
	}

	public String getTareas() {
		return tareas;
	}

	public void setTareas(String tareas) {
		this.tareas = tareas;
	}

	public Integer getContratoPcdActual() {
		return contratoPcdActual;
	}

	public void setContratoPcdActual(Integer contratoPcdActual) {
		this.contratoPcdActual = contratoPcdActual;
	}

	public Integer getContratoPcdAntes() {
		return contratoPcdAntes;
	}

	public void setContratoPcdAntes(Integer contratoPcdAntes) {
		this.contratoPcdAntes = contratoPcdAntes;
	}

	public Integer getInstalacionAdecuada() {
		return instalacionAdecuada;
	}

	public void setInstalacionAdecuada(Integer instalacionAdecuada) {
		this.instalacionAdecuada = instalacionAdecuada;
	}

	public String getBarreras() {
		return barreras;
	}

	public void setBarreras(String barreras) {
		this.barreras = barreras;
	}

	public Integer getNroSuperiores() {
		return nroSuperiores;
	}

	public void setNroSuperiores(Integer nroSuperiores) {
		this.nroSuperiores = nroSuperiores;
	}

	public Integer getNroCompaneros() {
		return nroCompaneros;
	}

	public void setNroCompaneros(Integer nroCompaneros) {
		this.nroCompaneros = nroCompaneros;
	}

	public Integer getNroSubordinados() {
		return nroSubordinados;
	}

	public void setNroSubordinados(Integer nroSubordinados) {
		this.nroSubordinados = nroSubordinados;
	}

	public String getDescCompaneros() {
		return descCompaneros;
	}

	public void setDescCompaneros(String descCompaneros) {
		this.descCompaneros = descCompaneros;
	}

	public String getDescMoviliario() {
		return descMoviliario;
	}

	public void setDescMoviliario(String descMoviliario) {
		this.descMoviliario = descMoviliario;
	}

	public String getDescTecnologia() {
		return descTecnologia;
	}

	public void setDescTecnologia(String descTecnologia) {
		this.descTecnologia = descTecnologia;
	}

	public String getDescHerramientas() {
		return descHerramientas;
	}

	public void setDescHerramientas(String descHerramientas) {
		this.descHerramientas = descHerramientas;
	}

	public String getDescMaquinarias() {
		return descMaquinarias;
	}

	public void setDescMaquinarias(String descMaquinarias) {
		this.descMaquinarias = descMaquinarias;
	}

	public String getDescVehiculos() {
		return descVehiculos;
	}

	public void setDescVehiculos(String descVehiculos) {
		this.descVehiculos = descVehiculos;
	}

	public String getDescOtros() {
		return descOtros;
	}

	public void setDescOtros(String descOtros) {
		this.descOtros = descOtros;
	}

	public String getDescEntornoAmbiental() {
		return descEntornoAmbiental;
	}

	public void setDescEntornoAmbiental(String descEntornoAmbiental) {
		this.descEntornoAmbiental = descEntornoAmbiental;
	}

	public String getDescFactoresRiesgo() {
		return descFactoresRiesgo;
	}

	public void setDescFactoresRiesgo(String descFactoresRiesgo) {
		this.descFactoresRiesgo = descFactoresRiesgo;
	}

	public String getDescProyAjustes() {
		return descProyAjustes;
	}

	public void setDescProyAjustes(String descProyAjustes) {
		this.descProyAjustes = descProyAjustes;
	}

	public Integer getCuotaEmpleo() {
		return cuotaEmpleo;
	}

	public void setCuotaEmpleo(Integer cuotaEmpleo) {
		this.cuotaEmpleo = cuotaEmpleo;
	}

	public String getMotivoContratoOtros() {
		return motivoContratoOtros;
	}

	public void setMotivoContratoOtros(String motivoContratoOtros) {
		this.motivoContratoOtros = motivoContratoOtros;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Pedido [fechaRegistro=");
		builder.append(fechaRegistro);
		builder.append(", fechaCierre=");
		builder.append(fechaCierre);
		builder.append(", empleador=");
		builder.append(empleador);
		builder.append(", nombre=");
		builder.append(nombre);
		builder.append(", nroPuestosCubrir=");
		builder.append(nroPuestosCubrir);
		builder.append(", nroCandidatosEnviar=");
		builder.append(nroCandidatosEnviar);
		builder.append(", nombreContacto=");
		builder.append(nombreContacto);
		builder.append(", puestoContacto=");
		builder.append(puestoContacto);
		builder.append(", telefContacto=");
		builder.append(telefContacto);
		builder.append(", anexoContacto=");
		builder.append(anexoContacto);
		builder.append(", correoContacto=");
		builder.append(correoContacto);
		builder.append(", fechaIniEntrevista=");
		builder.append(fechaIniEntrevista);
		builder.append(", fechaFinEntrevista=");
		builder.append(fechaFinEntrevista);
		builder.append(", horarioEntrevista=");
		builder.append(horarioEntrevista);
		builder.append(", lugarEntrevista=");
		builder.append(lugarEntrevista);
		builder.append(", codTipoRemuneracion=");
		builder.append(codTipoRemuneracion);
		builder.append(", movilidad=");
		builder.append(movilidad);
		builder.append(", refrigerio=");
		builder.append(refrigerio);
		builder.append(", bonificacion=");
		builder.append(bonificacion);
		builder.append(", seguro=");
		builder.append(seguro);
		builder.append(", comisiones=");
		builder.append(comisiones);
		builder.append(", codTipoPuesto=");
		builder.append(codTipoPuesto);
		builder.append(", personalACargo=");
		builder.append(personalACargo);
		builder.append(", numPersonalACargo=");
		builder.append(numPersonalACargo);
		builder.append(", tareas=");
		builder.append(tareas);
		builder.append(", jornada=");
		builder.append(jornada);
		builder.append(", remuneracion=");
		builder.append(remuneracion);
		builder.append(", horario=");
		builder.append(horario);
		builder.append(", departamento=");
		builder.append(departamento);
		builder.append(", provincia=");
		builder.append(provincia);
		builder.append(", distrito=");
		builder.append(distrito);
		builder.append(", nombreLugarResidencia=");
		builder.append(nombreLugarResidencia);
		builder.append(", codEstudiosFormales=");
		builder.append(codEstudiosFormales);
		builder.append(", profesion=");
		builder.append(profesion);
		builder.append(", codGrado=");
		builder.append(codGrado);
		builder.append(", licenciaConducir=");
		builder.append(licenciaConducir);
		builder.append(", categoriaLicenciaConducir=");
		builder.append(categoriaLicenciaConducir);
		builder.append(", vehiculoPropio=");
		builder.append(vehiculoPropio);
		builder.append(", sexoPreferente=");
		builder.append(sexoPreferente);
		builder.append(", edadIni=");
		builder.append(edadIni);
		builder.append(", edadFin=");
		builder.append(edadFin);
		builder.append(", experienciaRequerida=");
		builder.append(experienciaRequerida);
		builder.append(", codTipoExperiencia=");
		builder.append(codTipoExperiencia);
		builder.append(", codTipoDiscapacidad=");
		builder.append(codTipoDiscapacidad);
		builder.append(", habilidad1=");
		builder.append(habilidad1);
		builder.append(", habilidad2=");
		builder.append(habilidad2);
		builder.append(", habilidad3=");
		builder.append(habilidad3);
		builder.append(", habilidad4=");
		builder.append(habilidad4);
		builder.append(", habilidad5=");
		builder.append(habilidad5);
		builder.append(", habilidad6=");
		builder.append(habilidad6);
		builder.append(", habilidad7=");
		builder.append(habilidad7);
		builder.append(", habilidad8=");
		builder.append(habilidad8);
		builder.append(", habilidad9=");
		builder.append(habilidad9);
		builder.append(", habilidad10=");
		builder.append(habilidad10);
		builder.append(", habilidad11=");
		builder.append(habilidad11);
		builder.append(", habilidad12a=");
		builder.append(habilidad12a);
		builder.append(", habilidad12b=");
		builder.append(habilidad12b);
		builder.append(", habilidad12c=");
		builder.append(habilidad12c);
		builder.append(", habilidad12d=");
		builder.append(habilidad12d);
		builder.append(", habilidad13=");
		builder.append(habilidad13);
		builder.append(", habilidad14a=");
		builder.append(habilidad14a);
		builder.append(", habilidad14b=");
		builder.append(habilidad14b);
		builder.append(", habilidad15=");
		builder.append(habilidad15);
		builder.append(", habilidad16=");
		builder.append(habilidad16);
		builder.append(", habilidad17=");
		builder.append(habilidad17);
		builder.append(", habilidad18=");
		builder.append(habilidad18);
		builder.append(", habilidad19=");
		builder.append(habilidad19);
		builder.append(", habilidad20=");
		builder.append(habilidad20);
		builder.append(", habilidad21=");
		builder.append(habilidad21);
		builder.append(", habilidad22=");
		builder.append(habilidad22);
		builder.append(", habilidad23=");
		builder.append(habilidad23);
		builder.append(", habilidad24=");
		builder.append(habilidad24);
		builder.append(", habilidad25=");
		builder.append(habilidad25);
		builder.append(", contratoPcdActual=");
		builder.append(contratoPcdActual);
		builder.append(", contratoPcdAntes=");
		builder.append(contratoPcdAntes);
		builder.append(", instalacionAdecuada=");
		builder.append(instalacionAdecuada);
		builder.append(", barreras=");
		builder.append(barreras);
		builder.append(", nroSuperiores=");
		builder.append(nroSuperiores);
		builder.append(", nroCompaneros=");
		builder.append(nroCompaneros);
		builder.append(", nroSubordinados=");
		builder.append(nroSubordinados);
		builder.append(", descCompaneros=");
		builder.append(descCompaneros);
		builder.append(", descMoviliario=");
		builder.append(descMoviliario);
		builder.append(", descTecnologia=");
		builder.append(descTecnologia);
		builder.append(", descHerramientas=");
		builder.append(descHerramientas);
		builder.append(", descMaquinarias=");
		builder.append(descMaquinarias);
		builder.append(", descVehiculos=");
		builder.append(descVehiculos);
		builder.append(", descOtros=");
		builder.append(descOtros);
		builder.append(", descEntornoAmbiental=");
		builder.append(descEntornoAmbiental);
		builder.append(", descFactoresRiesgo=");
		builder.append(descFactoresRiesgo);
		builder.append(", descProyAjustes=");
		builder.append(descProyAjustes);
		builder.append(", cuotaEmpleo=");
		builder.append(cuotaEmpleo);
		builder.append(", motivoContratoOtros=");
		builder.append(motivoContratoOtros);
		builder.append("]");
		return builder.toString();
	}

}
