package pe.gob.trabajo.pcd.modelo.dominio;

/**
 * PersonaDiscapacidad generated by hbm2java
 */
public class PersonaPerfilHabilidad extends BeanEntidadGenericoAutogenerado implements java.io.Serializable {

	private static final long serialVersionUID = -7270688949443077922L;

	private Persona persona;

	private Integer indPersonalPh1;
	private Integer indPersonalPh2;
	private Integer indPersonalPh3;
	private Integer indPersonalPh4;
	private Integer indPersonalPh5;
	private Integer indPersonalPh6;
	private Integer indPersonalPh7;
	private Integer indPersonalPh8;
	private Integer indPersonalPh9;
	private Integer indPersonalPh10;
	private Integer indPersonalPh11;
	private Integer indPersonalPh12;
	private Integer indPersonalPh13;
	private Integer indPersonalPh14;
	private Integer indPersonalPh15;
	private Integer indPersonalPh16;
	private Integer indPersonalPh17;
	private Integer indPersonalPh18;
	private Integer indPersonalPh19;
	private Integer indPersonalPh20;
	private Integer indPersonalPh21;
	private Integer indPersonalPh22;
	private Integer indPersonalPh23;
	private Integer indPersonalPh24;
	private Integer indPersonalPh25;
	private Integer indPersonalPh26;
	private Integer indPersonalPh27;
	private Integer indPersonalPh28;
	private Integer indPersonalPh29;

	// camm
	private Integer esUtilizaApoyo;
	// camm
	private String especificarApoyo;

	public Persona getPersona() {
		return persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	public Integer getIndPersonalPh1() {
		return indPersonalPh1;
	}

	public void setIndPersonalPh1(Integer indPersonalPh1) {
		this.indPersonalPh1 = indPersonalPh1;
	}

	public Integer getIndPersonalPh2() {
		return indPersonalPh2;
	}

	public void setIndPersonalPh2(Integer indPersonalPh2) {
		this.indPersonalPh2 = indPersonalPh2;
	}

	public Integer getIndPersonalPh3() {
		return indPersonalPh3;
	}

	public void setIndPersonalPh3(Integer indPersonalPh3) {
		this.indPersonalPh3 = indPersonalPh3;
	}

	public Integer getIndPersonalPh4() {
		return indPersonalPh4;
	}

	public void setIndPersonalPh4(Integer indPersonalPh4) {
		this.indPersonalPh4 = indPersonalPh4;
	}

	public Integer getIndPersonalPh5() {
		return indPersonalPh5;
	}

	public void setIndPersonalPh5(Integer indPersonalPh5) {
		this.indPersonalPh5 = indPersonalPh5;
	}

	public Integer getIndPersonalPh6() {
		return indPersonalPh6;
	}

	public void setIndPersonalPh6(Integer indPersonalPh6) {
		this.indPersonalPh6 = indPersonalPh6;
	}

	public Integer getIndPersonalPh7() {
		return indPersonalPh7;
	}

	public void setIndPersonalPh7(Integer indPersonalPh7) {
		this.indPersonalPh7 = indPersonalPh7;
	}

	public Integer getIndPersonalPh9() {
		return indPersonalPh9;
	}

	public void setIndPersonalPh9(Integer indPersonalPh9) {
		this.indPersonalPh9 = indPersonalPh9;
	}

	public Integer getIndPersonalPh10() {
		return indPersonalPh10;
	}

	public void setIndPersonalPh10(Integer indPersonalPh10) {
		this.indPersonalPh10 = indPersonalPh10;
	}

	public Integer getIndPersonalPh11() {
		return indPersonalPh11;
	}

	public void setIndPersonalPh11(Integer indPersonalPh11) {
		this.indPersonalPh11 = indPersonalPh11;
	}

	public Integer getIndPersonalPh12() {
		return indPersonalPh12;
	}

	public void setIndPersonalPh12(Integer indPersonalPh12) {
		this.indPersonalPh12 = indPersonalPh12;
	}

	public Integer getIndPersonalPh13() {
		return indPersonalPh13;
	}

	public void setIndPersonalPh13(Integer indPersonalPh13) {
		this.indPersonalPh13 = indPersonalPh13;
	}

	public Integer getIndPersonalPh14() {
		return indPersonalPh14;
	}

	public void setIndPersonalPh14(Integer indPersonalPh14) {
		this.indPersonalPh14 = indPersonalPh14;
	}

	public Integer getIndPersonalPh15() {
		return indPersonalPh15;
	}

	public void setIndPersonalPh15(Integer indPersonalPh15) {
		this.indPersonalPh15 = indPersonalPh15;
	}

	public Integer getIndPersonalPh16() {
		return indPersonalPh16;
	}

	public void setIndPersonalPh16(Integer indPersonalPh16) {
		this.indPersonalPh16 = indPersonalPh16;
	}

	public Integer getIndPersonalPh17() {
		return indPersonalPh17;
	}

	public void setIndPersonalPh17(Integer indPersonalPh17) {
		this.indPersonalPh17 = indPersonalPh17;
	}

	public Integer getIndPersonalPh18() {
		return indPersonalPh18;
	}

	public void setIndPersonalPh18(Integer indPersonalPh18) {
		this.indPersonalPh18 = indPersonalPh18;
	}

	public Integer getIndPersonalPh19() {
		return indPersonalPh19;
	}

	public void setIndPersonalPh19(Integer indPersonalPh19) {
		this.indPersonalPh19 = indPersonalPh19;
	}

	public Integer getIndPersonalPh20() {
		return indPersonalPh20;
	}

	public void setIndPersonalPh20(Integer indPersonalPh20) {
		this.indPersonalPh20 = indPersonalPh20;
	}

	public Integer getIndPersonalPh21() {
		return indPersonalPh21;
	}

	public void setIndPersonalPh21(Integer indPersonalPh21) {
		this.indPersonalPh21 = indPersonalPh21;
	}

	public Integer getIndPersonalPh22() {
		return indPersonalPh22;
	}

	public void setIndPersonalPh22(Integer indPersonalPh22) {
		this.indPersonalPh22 = indPersonalPh22;
	}

	public Integer getIndPersonalPh23() {
		return indPersonalPh23;
	}

	public void setIndPersonalPh23(Integer indPersonalPh23) {
		this.indPersonalPh23 = indPersonalPh23;
	}

	public Integer getIndPersonalPh24() {
		return indPersonalPh24;
	}

	public void setIndPersonalPh24(Integer indPersonalPh24) {
		this.indPersonalPh24 = indPersonalPh24;
	}

	public Integer getIndPersonalPh25() {
		return indPersonalPh25;
	}

	public void setIndPersonalPh25(Integer indPersonalPh25) {
		this.indPersonalPh25 = indPersonalPh25;
	}

	public Integer getIndPersonalPh26() {
		return indPersonalPh26;
	}

	public void setIndPersonalPh26(Integer indPersonalPh26) {
		this.indPersonalPh26 = indPersonalPh26;
	}

	public Integer getIndPersonalPh27() {
		return indPersonalPh27;
	}

	public void setIndPersonalPh27(Integer indPersonalPh27) {
		this.indPersonalPh27 = indPersonalPh27;
	}

	public Integer getIndPersonalPh28() {
		return indPersonalPh28;
	}

	public void setIndPersonalPh28(Integer indPersonalPh28) {
		this.indPersonalPh28 = indPersonalPh28;
	}

	public Integer getIndPersonalPh29() {
		return indPersonalPh29;
	}

	public void setIndPersonalPh29(Integer indPersonalPh29) {
		this.indPersonalPh29 = indPersonalPh29;
	}

	public Integer getEsUtilizaApoyo() {

		return (this.esUtilizaApoyo == null) ? 0 : esUtilizaApoyo;

	}

	public void setEsUtilizaApoyo(Integer esUtilizaApoyo) {
		this.esUtilizaApoyo = esUtilizaApoyo;
	}

	public String getEspecificarApoyo() {

		return especificarApoyo;
	}

	public void setEspecificarApoyo(String especificarApoyo) {
		this.especificarApoyo = especificarApoyo;
	}

	public Integer getIndPersonalPh8() {
		return indPersonalPh8;
	}

	public void setIndPersonalPh8(Integer indPersonalPh8) {
		this.indPersonalPh8 = indPersonalPh8;
	}

}
