package pe.gob.trabajo.pcd.modelo.dominio;

/**
 * PersonaCondicionesTrabajo generated by hbm2java
 */
public class PersonaCondicionesTrabajo extends BeanEntidadGenericoAutogenerado implements java.io.Serializable {

	private static final long serialVersionUID = -6937544418664685727L;

	private Persona persona;

	private Integer idLaborHabitual1;// camm
	private Integer idLaborHabitual2;// cam
	private Integer idLaborHabitual3;// cam
	private Integer idLaborHabitual4;// cam
	private Integer idLaborHabitual5;// cam
	private Integer timeSintrabajar;// camm
	private Integer nivelSintrabajar;// camm
	private Integer esAsesorado;// camm
	private Double pretencion;// camm
	private String obserbacionesAdicionales;

	/**
	 * @return the persona
	 */
	public Persona getPersona() {
		return persona;
	}

	/**
	 * @param persona
	 *            the persona to set
	 */
	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	public Integer getIdLaborHabitual1() {

		return idLaborHabitual1;
	}

	public void setIdLaborHabitual1(Integer idLaborHabitual1) {
		this.idLaborHabitual1 = idLaborHabitual1;
	}

	public Integer getIdLaborHabitual2() {
		return idLaborHabitual2;
	}

	public void setIdLaborHabitual2(Integer idLaborHabitual2) {
		this.idLaborHabitual2 = idLaborHabitual2;
	}

	public Integer getIdLaborHabitual3() {
		return idLaborHabitual3;
	}

	public void setIdLaborHabitual3(Integer idLaborHabitual3) {
		this.idLaborHabitual3 = idLaborHabitual3;
	}

	public Integer getIdLaborHabitual4() {
		return idLaborHabitual4;
	}

	public void setIdLaborHabitual4(Integer idLaborHabitual4) {
		this.idLaborHabitual4 = idLaborHabitual4;
	}

	public Integer getIdLaborHabitual5() {
		return idLaborHabitual5;
	}

	public void setIdLaborHabitual5(Integer idLaborHabitual5) {
		this.idLaborHabitual5 = idLaborHabitual5;
	}

	public Integer getTimeSintrabajar() {
		return timeSintrabajar;
	}

	public void setTimeSintrabajar(Integer timeSintrabajar) {
		this.timeSintrabajar = timeSintrabajar;
	}

	public Integer getNivelSintrabajar() {
		return nivelSintrabajar;
	}

	public void setNivelSintrabajar(Integer nivelSintrabajar) {
		this.nivelSintrabajar = nivelSintrabajar;
	}

	public Integer getEsAsesorado() {
		return (this.esAsesorado == null) ? 0 : esAsesorado;

	}

	public void setEsAsesorado(Integer esAsesorado) {
		this.esAsesorado = esAsesorado;
	}

	public Double getPretencion() {
		return pretencion;
	}

	public void setPretencion(Double pretencion) {
		this.pretencion = pretencion;
	}

	public String getObserbacionesAdicionales() {
		return obserbacionesAdicionales;
	}

	public void setObserbacionesAdicionales(String obserbacionesAdicionales) {
		this.obserbacionesAdicionales = obserbacionesAdicionales;
	}

}
