package pe.gob.trabajo.pcd.modelo.dominio;


/**
 * NecesidadApoyo generated by hbm2java
 */
public class PersonaNecesidadApoyo extends BeanEntidadGenericoAutogeneradoValidable implements java.io.Serializable {

	private static final long serialVersionUID = 2812562056307982637L;
	
	private Persona persona;
	private String propuesta;
	private Integer areaApoyo;
	/**
	 * @return the persona
	 */
	public Persona getPersona() {
		return persona;
	}
	/**
	 * @param persona the persona to set
	 */
	public void setPersona(Persona persona) {
		this.persona = persona;
	}
	/**
	 * @return the propuesta
	 */
	public String getPropuesta() {
		return propuesta;
	}
	/**
	 * @param propuesta the propuesta to set
	 */
	public void setPropuesta(String propuesta) {
		this.propuesta = propuesta;
	}
	/**
	 * @return the areaApoyo
	 */
	public Integer getAreaApoyo() {
		return areaApoyo;
	}
	/**
	 * @param areaApoyo the areaApoyo to set
	 */
	public void setAreaApoyo(Integer areaApoyo) {
		this.areaApoyo = areaApoyo;
	}
	
	
}
