package pe.gob.trabajo.pcd.modelo.dominio;


/**
 * PersonaDiscapacidad generated by hbm2java
 */
public class PersonaMotivacion extends BeanEntidadGenericoAutogenerado
		implements java.io.Serializable {
	
	private static final long serialVersionUID = -7270688949443077922L;
	
	private Persona persona;
	private String deseosTrabajar;
	private Boolean motivoExito;
	private Boolean motivoPoderAdquisitivo;
	private Boolean motivoGanarSalario;
	private Boolean motivoSerUtil;
	private Boolean motivoIndependencia;
	private Boolean motivoAutoestima;
	private Boolean motivoReconocimiento;
	private Boolean motivoRelacionarse;
	private Boolean motivoPracticaEstudiado;
	private Boolean motivoAprender;
	private Boolean motivoAyudarFamilia;
	private Boolean motivoDesaislamiento;
	
	private String confundeMotivacion;
	private String noExpresaMotivacion;
	private String motivosNoClaros;
	/**
	 * @return the persona
	 */
	public Persona getPersona() {
		return persona;
	}
	/**
	 * @param persona the persona to set
	 */
	public void setPersona(Persona persona) {
		this.persona = persona;
	}
	/**
	 * @return the deseosTrabajar
	 */
	public String getDeseosTrabajar() {
		return deseosTrabajar;
	}
	/**
	 * @param deseosTrabajar the deseosTrabajar to set
	 */
	public void setDeseosTrabajar(String deseosTrabajar) {
		this.deseosTrabajar = deseosTrabajar;
	}
	/**
	 * @return the motivoExito
	 */
	public Boolean getMotivoExito() {
		return motivoExito;
	}
	/**
	 * @param motivoExito the motivoExito to set
	 */
	public void setMotivoExito(Boolean motivoExito) {
		this.motivoExito = motivoExito;
	}
	/**
	 * @return the motivoPoderAdquisitivo
	 */
	public Boolean getMotivoPoderAdquisitivo() {
		return motivoPoderAdquisitivo;
	}
	/**
	 * @param motivoPoderAdquisitivo the motivoPoderAdquisitivo to set
	 */
	public void setMotivoPoderAdquisitivo(Boolean motivoPoderAdquisitivo) {
		this.motivoPoderAdquisitivo = motivoPoderAdquisitivo;
	}
	/**
	 * @return the motivoGanarSalario
	 */
	public Boolean getMotivoGanarSalario() {
		return motivoGanarSalario;
	}
	/**
	 * @param motivoGanarSalario the motivoGanarSalario to set
	 */
	public void setMotivoGanarSalario(Boolean motivoGanarSalario) {
		this.motivoGanarSalario = motivoGanarSalario;
	}
	/**
	 * @return the motivoSerUtil
	 */
	public Boolean getMotivoSerUtil() {
		return motivoSerUtil;
	}
	/**
	 * @param motivoSerUtil the motivoSerUtil to set
	 */
	public void setMotivoSerUtil(Boolean motivoSerUtil) {
		this.motivoSerUtil = motivoSerUtil;
	}
	/**
	 * @return the motivoIndependencia
	 */
	public Boolean getMotivoIndependencia() {
		return motivoIndependencia;
	}
	/**
	 * @param motivoIndependencia the motivoIndependencia to set
	 */
	public void setMotivoIndependencia(Boolean motivoIndependencia) {
		this.motivoIndependencia = motivoIndependencia;
	}
	/**
	 * @return the motivoAutoestima
	 */
	public Boolean getMotivoAutoestima() {
		return motivoAutoestima;
	}
	/**
	 * @param motivoAutoestima the motivoAutoestima to set
	 */
	public void setMotivoAutoestima(Boolean motivoAutoestima) {
		this.motivoAutoestima = motivoAutoestima;
	}
	/**
	 * @return the motivoReconocimiento
	 */
	public Boolean getMotivoReconocimiento() {
		return motivoReconocimiento;
	}
	/**
	 * @param motivoReconocimiento the motivoReconocimiento to set
	 */
	public void setMotivoReconocimiento(Boolean motivoReconocimiento) {
		this.motivoReconocimiento = motivoReconocimiento;
	}
	/**
	 * @return the motivoRelacionarse
	 */
	public Boolean getMotivoRelacionarse() {
		return motivoRelacionarse;
	}
	/**
	 * @param motivoRelacionarse the motivoRelacionarse to set
	 */
	public void setMotivoRelacionarse(Boolean motivoRelacionarse) {
		this.motivoRelacionarse = motivoRelacionarse;
	}
	/**
	 * @return the motivoPracticaEstudiado
	 */
	public Boolean getMotivoPracticaEstudiado() {
		return motivoPracticaEstudiado;
	}
	/**
	 * @param motivoPracticaEstudiado the motivoPracticaEstudiado to set
	 */
	public void setMotivoPracticaEstudiado(Boolean motivoPracticaEstudiado) {
		this.motivoPracticaEstudiado = motivoPracticaEstudiado;
	}
	/**
	 * @return the motivoAprender
	 */
	public Boolean getMotivoAprender() {
		return motivoAprender;
	}
	/**
	 * @param motivoAprender the motivoAprender to set
	 */
	public void setMotivoAprender(Boolean motivoAprender) {
		this.motivoAprender = motivoAprender;
	}
	/**
	 * @return the motivoAyudarFamilia
	 */
	public Boolean getMotivoAyudarFamilia() {
		return motivoAyudarFamilia;
	}
	/**
	 * @param motivoAyudarFamilia the motivoAyudarFamilia to set
	 */
	public void setMotivoAyudarFamilia(Boolean motivoAyudarFamilia) {
		this.motivoAyudarFamilia = motivoAyudarFamilia;
	}
	/**
	 * @return the motivoDesaislamiento
	 */
	public Boolean getMotivoDesaislamiento() {
		return motivoDesaislamiento;
	}
	/**
	 * @param motivoDesaislamiento the motivoDesaislamiento to set
	 */
	public void setMotivoDesaislamiento(Boolean motivoDesaislamiento) {
		this.motivoDesaislamiento = motivoDesaislamiento;
	}
	/**
	 * @return the confundeMotivacion
	 */
	public String getConfundeMotivacion() {
		return confundeMotivacion;
	}
	/**
	 * @param confundeMotivacion the confundeMotivacion to set
	 */
	public void setConfundeMotivacion(String confundeMotivacion) {
		this.confundeMotivacion = confundeMotivacion;
	}
	/**
	 * @return the noExpresaMotivacion
	 */
	public String getNoExpresaMotivacion() {
		return noExpresaMotivacion;
	}
	/**
	 * @param noExpresaMotivacion the noExpresaMotivacion to set
	 */
	public void setNoExpresaMotivacion(String noExpresaMotivacion) {
		this.noExpresaMotivacion = noExpresaMotivacion;
	}
	/**
	 * @return the motivosNoClaros
	 */
	public String getMotivosNoClaros() {
		return motivosNoClaros;
	}
	/**
	 * @param motivosNoClaros the motivosNoClaros to set
	 */
	public void setMotivosNoClaros(String motivosNoClaros) {
		this.motivosNoClaros = motivosNoClaros;
	}
	

}
