package pe.gob.trabajo.pcd.modelo.dominio;


/**
 * PersonaIntegranteFamilia generated by hbm2java
 */
public class PersonaIntegranteFamilia extends BeanEntidadGenericoAutogeneradoValidable implements java.io.Serializable {

	private static final long serialVersionUID = 2638171757756183192L;
	
	private Persona persona;
	private String nombreIntegrante;
	private Integer edad;
	private Integer codigoParentesco;
	private Integer codigoOcupacion;
	private String descripcionOcupacion;
	private Boolean enActividad;
	private Boolean resideEnViviendaFamiliar;
	/**
	 * @return the persona
	 */
	public Persona getPersona() {
		return persona;
	}
	/**
	 * @param persona the persona to set
	 */
	public void setPersona(Persona persona) {
		this.persona = persona;
	}
	/**
	 * @return the nombreIntegrante
	 */
	public String getNombreIntegrante() {
		return nombreIntegrante;
	}
	/**
	 * @param nombreIntegrante the nombreIntegrante to set
	 */
	public void setNombreIntegrante(String nombreIntegrante) {
		this.nombreIntegrante = nombreIntegrante;
	}
	/**
	 * @return the edad
	 */
	public Integer getEdad() {
		return edad;
	}
	/**
	 * @param edad the edad to set
	 */
	public void setEdad(Integer edad) {
		this.edad = edad;
	}
	/**
	 * @return the codigoParentesco
	 */
	public Integer getCodigoParentesco() {
		return codigoParentesco;
	}
	/**
	 * @param codigoParentesco the codigoParentesco to set
	 */
	public void setCodigoParentesco(Integer codigoParentesco) {
		this.codigoParentesco = codigoParentesco;
	}
	/**
	 * @return the codigoOcupacion
	 */
	public Integer getCodigoOcupacion() {
		return codigoOcupacion;
	}
	/**
	 * @param codigoOcupacion the codigoOcupacion to set
	 */
	public void setCodigoOcupacion(Integer codigoOcupacion) {
		this.codigoOcupacion = codigoOcupacion;
	}
	/**
	 * @return the descripcionOcupacion
	 */
	public String getDescripcionOcupacion() {
		return descripcionOcupacion;
	}
	/**
	 * @param descripcionOcupacion the descripcionOcupacion to set
	 */
	public void setDescripcionOcupacion(String descripcionOcupacion) {
		this.descripcionOcupacion = descripcionOcupacion;
	}
	/**
	 * @return the enActividad
	 */
	public Boolean getEnActividad() {
		return enActividad;
	}
	/**
	 * @param enActividad the enActividad to set
	 */
	public void setEnActividad(Boolean enActividad) {
		this.enActividad = enActividad;
	}
	/**
	 * @return the resideEnViviendaFamiliar
	 */
	public Boolean getResideEnViviendaFamiliar() {
		return resideEnViviendaFamiliar;
	}
	/**
	 * @param resideEnViviendaFamiliar the resideEnViviendaFamiliar to set
	 */
	public void setResideEnViviendaFamiliar(Boolean resideEnViviendaFamiliar) {
		this.resideEnViviendaFamiliar = resideEnViviendaFamiliar;
	}
	
}
