package pe.gob.trabajo.pcd.modelo.dominio;

import java.util.Date;

/**
 * PersonaDiscapacidad generated by hbm2java
 */
public class PersonaDiscapacidad extends BeanEntidadGenericoAutogenerado
		implements java.io.Serializable {
	
	private static final long serialVersionUID = 3593831126902991965L;
	
	private Persona persona;
	private String condicion;
	private String inscritoConadis;
	private Double certificadoPorcentajeDiscapacidad;
	private Date certificadoVigenciaHasta;
	private String concienteDiscapacidad;
	private String nombraCaracteristicas;
	private String caracteristicasDiscapacidad;
	private String informacionDiscapacidad;
	/**
	 * @return the persona
	 */
	public Persona getPersona() {
		return persona;
	}
	/**
	 * @param persona the persona to set
	 */
	public void setPersona(Persona persona) {
		this.persona = persona;
	}
	/**
	 * @return the condicion
	 */
	public String getCondicion() {
		return condicion;
	}
	/**
	 * @param condicion the condicion to set
	 */
	public void setCondicion(String condicion) {
		this.condicion = condicion;
	}
	/**
	 * @return the inscritoConadis
	 */
	public String getInscritoConadis() {
		return inscritoConadis;
	}
	/**
	 * @param inscritoConadis the inscritoConadis to set
	 */
	public void setInscritoConadis(String inscritoConadis) {
		this.inscritoConadis = inscritoConadis;
	}
	/**
	 * @return the certificadoPorcentajeDiscapacidad
	 */
	public Double getCertificadoPorcentajeDiscapacidad() {
		return certificadoPorcentajeDiscapacidad;
	}
	/**
	 * @param certificadoPorcentajeDiscapacidad the certificadoPorcentajeDiscapacidad to set
	 */
	public void setCertificadoPorcentajeDiscapacidad(
			Double certificadoPorcentajeDiscapacidad) {
		this.certificadoPorcentajeDiscapacidad = certificadoPorcentajeDiscapacidad;
	}
	/**
	 * @return the certificadoVigenciaHasta
	 */
	public Date getCertificadoVigenciaHasta() {
		return certificadoVigenciaHasta;
	}
	/**
	 * @param certificadoVigenciaHasta the certificadoVigenciaHasta to set
	 */
	public void setCertificadoVigenciaHasta(Date certificadoVigenciaHasta) {
		this.certificadoVigenciaHasta = certificadoVigenciaHasta;
	}
	/**
	 * @return the concienteDiscapacidad
	 */
	public String getConcienteDiscapacidad() {
		return concienteDiscapacidad;
	}
	/**
	 * @param concienteDiscapacidad the concienteDiscapacidad to set
	 */
	public void setConcienteDiscapacidad(String concienteDiscapacidad) {
		this.concienteDiscapacidad = concienteDiscapacidad;
	}
	/**
	 * @return the nombraCaracteristicas
	 */
	public String getNombraCaracteristicas() {
		return nombraCaracteristicas;
	}
	/**
	 * @param nombraCaracteristicas the nombraCaracteristicas to set
	 */
	public void setNombraCaracteristicas(String nombraCaracteristicas) {
		this.nombraCaracteristicas = nombraCaracteristicas;
	}
	/**
	 * @return the caracteristicasDiscapacidad
	 */
	public String getCaracteristicasDiscapacidad() {
		return caracteristicasDiscapacidad;
	}
	/**
	 * @param caracteristicasDiscapacidad the caracteristicasDiscapacidad to set
	 */
	public void setCaracteristicasDiscapacidad(String caracteristicasDiscapacidad) {
		this.caracteristicasDiscapacidad = caracteristicasDiscapacidad;
	}
	/**
	 * @return the informacionDiscapacidad
	 */
	public String getInformacionDiscapacidad() {
		return informacionDiscapacidad;
	}
	/**
	 * @param informacionDiscapacidad the informacionDiscapacidad to set
	 */
	public void setInformacionDiscapacidad(String informacionDiscapacidad) {
		this.informacionDiscapacidad = informacionDiscapacidad;
	}

}
