package pe.gob.trabajo.pcd.modelo.dominio;

/**
 * PersonaDiscapacidad generated by hbm2java
 */
public class PersonaEvaluacionPerfil extends BeanEntidadGenericoAutogenerado implements java.io.Serializable {

	private static final long serialVersionUID = -7270688949443077922L;

	private Persona persona;

	private Integer indPersonalCp1;
	private Integer indPersonalMe1;
	private Integer indPersonalCp2;
	private Integer indPersonalMe2;
	private Integer indPersonalCp3;
	private Integer indPersonalMe3;
	private Integer indPersonalCp4;
	private Integer indPersonalMe4;
	private Integer indPersonalCp5;
	private Integer indPersonalMe5;
	private Integer indPersonalCp6;
	private Integer indPersonalMe6;
	private Integer indPersonalCp7;
	private Integer indPersonalMe7;
	private Integer indPersonalCp8;
	private Integer indPersonalMe8;
	private Integer indPersonalCp9;
	private Integer indPersonalMe9;
	private Integer indPersonalCp10;
	private Integer indPersonalMe10;
	private Integer indPersonalCp11;
	private Integer indPersonalMe11;
	private Integer indPersonalCp12;
	private Integer indPersonalMe12;
	private Integer indPersonalCp13;
	private Integer indPersonalMe13;
	private Integer indPersonalCp14;
	private Integer indPersonalMe14;
	private Integer indPersonalCp15;
	private Integer indPersonalMe15;
	private Integer indPersonalCp16;
	private Integer indPersonalMe16;
	private Integer indPersonalCp17;
	private Integer indPersonalMe17;
	private Integer indPersonalCp18;
	private Integer indPersonalMe18;

	private Integer indSocialCp1;
	private Integer indSocialMe1;
	private Integer indSocialCp2;
	private Integer indSocialMe2;
	private Integer indSocialCp3;
	private Integer indSocialMe3;
	private Integer indSocialCp4;
	private Integer indSocialMe4;
	private Integer indSocialCp5;
	private Integer indSocialMe5;
	private Integer indSocialCp6;
	private Integer indSocialMe6;
	private Integer indSocialCp7;
	private Integer indSocialMe7;
	private Integer indSocialCp8;
	private Integer indSocialMe8;
	private Integer indSocialCp9;
	private Integer indSocialMe9;
	private Integer indSocialCp10;
	private Integer indSocialMe10;
	private Integer indSocialCp11;
	private Integer indSocialMe11;
	private Integer indSocialCp12;
	private Integer indSocialMe12;
	private Integer indSocialCp13;
	private Integer indSocialMe13;
	private Integer indSocialCp14;
	private Integer indSocialMe14;
	private Integer indSocialCp15;
	private Integer indSocialMe15;
	private Integer indSocialCp16;
	private Integer indSocialMe16;
	private Integer indSocialCp17;
	private Integer indSocialMe17;
	private Integer indSocialCp18;
	private Integer indSocialMe18;

	private Integer indPrelaboralCp1;
	private Integer indPrelaboralMe1;
	private Integer indPrelaboralCp2;
	private Integer indPrelaboralMe2;
	private Integer indPrelaboralCp3;
	private Integer indPrelaboralMe3;
	private Integer indPrelaboralCp4;
	private Integer indPrelaboralMe4;
	private Integer indPrelaboralCp5;
	private Integer indPrelaboralMe5;
	private Integer indPrelaboralCp6;
	private Integer indPrelaboralMe6;
	private Integer indPrelaboralCp7;
	private Integer indPrelaboralMe7;
	private Integer indPrelaboralCp8;
	private Integer indPrelaboralMe8;
	private Integer indPrelaboralCp9;
	private Integer indPrelaboralMe9;
	private Integer indPrelaboralCp10;
	private Integer indPrelaboralMe10;
	private Integer indPrelaboralCp11;
	private Integer indPrelaboralMe11;
	private Integer indPrelaboralCp12;
	private Integer indPrelaboralMe12;
	private Integer indPrelaboralCp13;
	private Integer indPrelaboralMe13;
	private Integer indPrelaboralCp14;
	private Integer indPrelaboralMe14;
	private Integer indPrelaboralCp15;
	private Integer indPrelaboralMe15;
	private Integer indPrelaboralCp16;
	private Integer indPrelaboralMe16;
	private Integer indPrelaboralCp17;
	private Integer indPrelaboralMe17;
	private Integer indPrelaboralCp18;
	private Integer indPrelaboralMe18;

	/**
	 * @return the persona
	 */
	public Persona getPersona() {
		return persona;
	}

	/**
	 * @param persona
	 *            the persona to set
	 */
	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	public Integer getIndPersonalCp1() {
		return indPersonalCp1;
	}

	public void setIndPersonalCp1(Integer indPersonalCp1) {
		this.indPersonalCp1 = indPersonalCp1;
	}

	public Integer getIndPersonalMe1() {
		return indPersonalMe1;
	}

	public void setIndPersonalMe1(Integer indPersonalMe1) {
		this.indPersonalMe1 = indPersonalMe1;
	}

	public Integer getIndPersonalCp2() {
		return indPersonalCp2;
	}

	public void setIndPersonalCp2(Integer indPersonalCp2) {
		this.indPersonalCp2 = indPersonalCp2;
	}

	public Integer getIndPersonalMe2() {
		return indPersonalMe2;
	}

	public void setIndPersonalMe2(Integer indPersonalMe2) {
		this.indPersonalMe2 = indPersonalMe2;
	}

	public Integer getIndPersonalCp3() {
		return indPersonalCp3;
	}

	public void setIndPersonalCp3(Integer indPersonalCp3) {
		this.indPersonalCp3 = indPersonalCp3;
	}

	public Integer getIndPersonalMe3() {
		return indPersonalMe3;
	}

	public void setIndPersonalMe3(Integer indPersonalMe3) {
		this.indPersonalMe3 = indPersonalMe3;
	}

	public Integer getIndPersonalCp4() {
		return indPersonalCp4;
	}

	public void setIndPersonalCp4(Integer indPersonalCp4) {
		this.indPersonalCp4 = indPersonalCp4;
	}

	public Integer getIndPersonalMe4() {
		return indPersonalMe4;
	}

	public void setIndPersonalMe4(Integer indPersonalMe4) {
		this.indPersonalMe4 = indPersonalMe4;
	}

	public Integer getIndPersonalCp5() {
		return indPersonalCp5;
	}

	public void setIndPersonalCp5(Integer indPersonalCp5) {
		this.indPersonalCp5 = indPersonalCp5;
	}

	public Integer getIndPersonalMe5() {
		return indPersonalMe5;
	}

	public void setIndPersonalMe5(Integer indPersonalMe5) {
		this.indPersonalMe5 = indPersonalMe5;
	}

	public Integer getIndPersonalCp6() {
		return indPersonalCp6;
	}

	public void setIndPersonalCp6(Integer indPersonalCp6) {
		this.indPersonalCp6 = indPersonalCp6;
	}

	public Integer getIndPersonalMe6() {
		return indPersonalMe6;
	}

	public void setIndPersonalMe6(Integer indPersonalMe6) {
		this.indPersonalMe6 = indPersonalMe6;
	}

	public Integer getIndPersonalCp7() {
		return indPersonalCp7;
	}

	public void setIndPersonalCp7(Integer indPersonalCp7) {
		this.indPersonalCp7 = indPersonalCp7;
	}

	public Integer getIndPersonalMe7() {
		return indPersonalMe7;
	}

	public void setIndPersonalMe7(Integer indPersonalMe7) {
		this.indPersonalMe7 = indPersonalMe7;
	}

	public Integer getIndPersonalCp8() {
		return indPersonalCp8;
	}

	public void setIndPersonalCp8(Integer indPersonalCp8) {
		this.indPersonalCp8 = indPersonalCp8;
	}

	public Integer getIndPersonalMe8() {
		return indPersonalMe8;
	}

	public void setIndPersonalMe8(Integer indPersonalMe8) {
		this.indPersonalMe8 = indPersonalMe8;
	}

	public Integer getIndPersonalCp9() {
		return indPersonalCp9;
	}

	public void setIndPersonalCp9(Integer indPersonalCp9) {
		this.indPersonalCp9 = indPersonalCp9;
	}

	public Integer getIndPersonalMe9() {
		return indPersonalMe9;
	}

	public void setIndPersonalMe9(Integer indPersonalMe9) {
		this.indPersonalMe9 = indPersonalMe9;
	}

	public Integer getIndPersonalCp10() {
		return indPersonalCp10;
	}

	public void setIndPersonalCp10(Integer indPersonalCp10) {
		this.indPersonalCp10 = indPersonalCp10;
	}

	public Integer getIndPersonalMe10() {
		return indPersonalMe10;
	}

	public void setIndPersonalMe10(Integer indPersonalMe10) {
		this.indPersonalMe10 = indPersonalMe10;
	}

	public Integer getIndPersonalCp11() {
		return indPersonalCp11;
	}

	public void setIndPersonalCp11(Integer indPersonalCp11) {
		this.indPersonalCp11 = indPersonalCp11;
	}

	public Integer getIndPersonalMe11() {
		return indPersonalMe11;
	}

	public void setIndPersonalMe11(Integer indPersonalMe11) {
		this.indPersonalMe11 = indPersonalMe11;
	}

	public Integer getIndPersonalCp12() {
		return indPersonalCp12;
	}

	public void setIndPersonalCp12(Integer indPersonalCp12) {
		this.indPersonalCp12 = indPersonalCp12;
	}

	public Integer getIndPersonalMe12() {
		return indPersonalMe12;
	}

	public void setIndPersonalMe12(Integer indPersonalMe12) {
		this.indPersonalMe12 = indPersonalMe12;
	}

	public Integer getIndPersonalCp13() {
		return indPersonalCp13;
	}

	public void setIndPersonalCp13(Integer indPersonalCp13) {
		this.indPersonalCp13 = indPersonalCp13;
	}

	public Integer getIndPersonalMe13() {
		return indPersonalMe13;
	}

	public void setIndPersonalMe13(Integer indPersonalMe13) {
		this.indPersonalMe13 = indPersonalMe13;
	}

	public Integer getIndPersonalCp14() {
		return indPersonalCp14;
	}

	public void setIndPersonalCp14(Integer indPersonalCp14) {
		this.indPersonalCp14 = indPersonalCp14;
	}

	public Integer getIndPersonalMe14() {
		return indPersonalMe14;
	}

	public void setIndPersonalMe14(Integer indPersonalMe14) {
		this.indPersonalMe14 = indPersonalMe14;
	}

	public Integer getIndPersonalCp15() {
		return indPersonalCp15;
	}

	public void setIndPersonalCp15(Integer indPersonalCp15) {
		this.indPersonalCp15 = indPersonalCp15;
	}

	public Integer getIndPersonalMe15() {
		return indPersonalMe15;
	}

	public void setIndPersonalMe15(Integer indPersonalMe15) {
		this.indPersonalMe15 = indPersonalMe15;
	}

	public Integer getIndPersonalCp16() {
		return indPersonalCp16;
	}

	public void setIndPersonalCp16(Integer indPersonalCp16) {
		this.indPersonalCp16 = indPersonalCp16;
	}

	public Integer getIndPersonalMe16() {
		return indPersonalMe16;
	}

	public void setIndPersonalMe16(Integer indPersonalMe16) {
		this.indPersonalMe16 = indPersonalMe16;
	}

	public Integer getIndPersonalCp17() {
		return indPersonalCp17;
	}

	public void setIndPersonalCp17(Integer indPersonalCp17) {
		this.indPersonalCp17 = indPersonalCp17;
	}

	public Integer getIndPersonalMe17() {
		return indPersonalMe17;
	}

	public void setIndPersonalMe17(Integer indPersonalMe17) {
		this.indPersonalMe17 = indPersonalMe17;
	}

	public Integer getIndPersonalCp18() {
		return indPersonalCp18;
	}

	public void setIndPersonalCp18(Integer indPersonalCp18) {
		this.indPersonalCp18 = indPersonalCp18;
	}

	public Integer getIndPersonalMe18() {
		return indPersonalMe18;
	}

	public void setIndPersonalMe18(Integer indPersonalMe18) {
		this.indPersonalMe18 = indPersonalMe18;
	}

	public Integer getIndSocialCp1() {
		return indSocialCp1;
	}

	public void setIndSocialCp1(Integer indSocialCp1) {
		this.indSocialCp1 = indSocialCp1;
	}

	public Integer getIndSocialMe1() {
		return indSocialMe1;
	}

	public void setIndSocialMe1(Integer indSocialMe1) {
		this.indSocialMe1 = indSocialMe1;
	}

	public Integer getIndSocialCp2() {
		return indSocialCp2;
	}

	public void setIndSocialCp2(Integer indSocialCp2) {
		this.indSocialCp2 = indSocialCp2;
	}

	public Integer getIndSocialMe2() {
		return indSocialMe2;
	}

	public void setIndSocialMe2(Integer indSocialMe2) {
		this.indSocialMe2 = indSocialMe2;
	}

	public Integer getIndSocialCp3() {
		return indSocialCp3;
	}

	public void setIndSocialCp3(Integer indSocialCp3) {
		this.indSocialCp3 = indSocialCp3;
	}

	public Integer getIndSocialMe3() {
		return indSocialMe3;
	}

	public void setIndSocialMe3(Integer indSocialMe3) {
		this.indSocialMe3 = indSocialMe3;
	}

	public Integer getIndSocialCp4() {
		return indSocialCp4;
	}

	public void setIndSocialCp4(Integer indSocialCp4) {
		this.indSocialCp4 = indSocialCp4;
	}

	public Integer getIndSocialMe4() {
		return indSocialMe4;
	}

	public void setIndSocialMe4(Integer indSocialMe4) {
		this.indSocialMe4 = indSocialMe4;
	}

	public Integer getIndSocialCp5() {
		return indSocialCp5;
	}

	public void setIndSocialCp5(Integer indSocialCp5) {
		this.indSocialCp5 = indSocialCp5;
	}

	public Integer getIndSocialMe5() {
		return indSocialMe5;
	}

	public void setIndSocialMe5(Integer indSocialMe5) {
		this.indSocialMe5 = indSocialMe5;
	}

	public Integer getIndSocialCp6() {
		return indSocialCp6;
	}

	public void setIndSocialCp6(Integer indSocialCp6) {
		this.indSocialCp6 = indSocialCp6;
	}

	public Integer getIndSocialMe6() {
		return indSocialMe6;
	}

	public void setIndSocialMe6(Integer indSocialMe6) {
		this.indSocialMe6 = indSocialMe6;
	}

	public Integer getIndSocialCp7() {
		return indSocialCp7;
	}

	public void setIndSocialCp7(Integer indSocialCp7) {
		this.indSocialCp7 = indSocialCp7;
	}

	public Integer getIndSocialMe7() {
		return indSocialMe7;
	}

	public void setIndSocialMe7(Integer indSocialMe7) {
		this.indSocialMe7 = indSocialMe7;
	}

	public Integer getIndSocialCp8() {
		return indSocialCp8;
	}

	public void setIndSocialCp8(Integer indSocialCp8) {
		this.indSocialCp8 = indSocialCp8;
	}

	public Integer getIndSocialMe8() {
		return indSocialMe8;
	}

	public void setIndSocialMe8(Integer indSocialMe8) {
		this.indSocialMe8 = indSocialMe8;
	}

	public Integer getIndSocialCp9() {
		return indSocialCp9;
	}

	public void setIndSocialCp9(Integer indSocialCp9) {
		this.indSocialCp9 = indSocialCp9;
	}

	public Integer getIndSocialMe9() {
		return indSocialMe9;
	}

	public void setIndSocialMe9(Integer indSocialMe9) {
		this.indSocialMe9 = indSocialMe9;
	}

	public Integer getIndSocialCp10() {
		return indSocialCp10;
	}

	public void setIndSocialCp10(Integer indSocialCp10) {
		this.indSocialCp10 = indSocialCp10;
	}

	public Integer getIndSocialMe10() {
		return indSocialMe10;
	}

	public void setIndSocialMe10(Integer indSocialMe10) {
		this.indSocialMe10 = indSocialMe10;
	}

	public Integer getIndSocialCp11() {
		return indSocialCp11;
	}

	public void setIndSocialCp11(Integer indSocialCp11) {
		this.indSocialCp11 = indSocialCp11;
	}

	public Integer getIndSocialMe11() {
		return indSocialMe11;
	}

	public void setIndSocialMe11(Integer indSocialMe11) {
		this.indSocialMe11 = indSocialMe11;
	}

	public Integer getIndSocialCp12() {
		return indSocialCp12;
	}

	public void setIndSocialCp12(Integer indSocialCp12) {
		this.indSocialCp12 = indSocialCp12;
	}

	public Integer getIndSocialMe12() {
		return indSocialMe12;
	}

	public void setIndSocialMe12(Integer indSocialMe12) {
		this.indSocialMe12 = indSocialMe12;
	}

	public Integer getIndSocialCp13() {
		return indSocialCp13;
	}

	public void setIndSocialCp13(Integer indSocialCp13) {
		this.indSocialCp13 = indSocialCp13;
	}

	public Integer getIndSocialMe13() {
		return indSocialMe13;
	}

	public void setIndSocialMe13(Integer indSocialMe13) {
		this.indSocialMe13 = indSocialMe13;
	}

	public Integer getIndSocialCp14() {
		return indSocialCp14;
	}

	public void setIndSocialCp14(Integer indSocialCp14) {
		this.indSocialCp14 = indSocialCp14;
	}

	public Integer getIndSocialMe14() {
		return indSocialMe14;
	}

	public void setIndSocialMe14(Integer indSocialMe14) {
		this.indSocialMe14 = indSocialMe14;
	}

	public Integer getIndSocialCp15() {
		return indSocialCp15;
	}

	public void setIndSocialCp15(Integer indSocialCp15) {
		this.indSocialCp15 = indSocialCp15;
	}

	public Integer getIndSocialMe15() {
		return indSocialMe15;
	}

	public void setIndSocialMe15(Integer indSocialMe15) {
		this.indSocialMe15 = indSocialMe15;
	}

	public Integer getIndSocialCp16() {
		return indSocialCp16;
	}

	public void setIndSocialCp16(Integer indSocialCp16) {
		this.indSocialCp16 = indSocialCp16;
	}

	public Integer getIndSocialMe16() {
		return indSocialMe16;
	}

	public void setIndSocialMe16(Integer indSocialMe16) {
		this.indSocialMe16 = indSocialMe16;
	}

	public Integer getIndSocialCp17() {
		return indSocialCp17;
	}

	public void setIndSocialCp17(Integer indSocialCp17) {
		this.indSocialCp17 = indSocialCp17;
	}

	public Integer getIndSocialMe17() {
		return indSocialMe17;
	}

	public void setIndSocialMe17(Integer indSocialMe17) {
		this.indSocialMe17 = indSocialMe17;
	}

	public Integer getIndSocialCp18() {
		return indSocialCp18;
	}

	public void setIndSocialCp18(Integer indSocialCp18) {
		this.indSocialCp18 = indSocialCp18;
	}

	public Integer getIndSocialMe18() {
		return indSocialMe18;
	}

	public void setIndSocialMe18(Integer indSocialMe18) {
		this.indSocialMe18 = indSocialMe18;
	}

	public Integer getIndPrelaboralCp1() {
		return indPrelaboralCp1;
	}

	public void setIndPrelaboralCp1(Integer indPrelaboralCp1) {
		this.indPrelaboralCp1 = indPrelaboralCp1;
	}

	public Integer getIndPrelaboralMe1() {
		return indPrelaboralMe1;
	}

	public void setIndPrelaboralMe1(Integer indPrelaboralMe1) {
		this.indPrelaboralMe1 = indPrelaboralMe1;
	}

	public Integer getIndPrelaboralCp2() {
		return indPrelaboralCp2;
	}

	public void setIndPrelaboralCp2(Integer indPrelaboralCp2) {
		this.indPrelaboralCp2 = indPrelaboralCp2;
	}

	public Integer getIndPrelaboralMe2() {
		return indPrelaboralMe2;
	}

	public void setIndPrelaboralMe2(Integer indPrelaboralMe2) {
		this.indPrelaboralMe2 = indPrelaboralMe2;
	}

	public Integer getIndPrelaboralCp3() {
		return indPrelaboralCp3;
	}

	public void setIndPrelaboralCp3(Integer indPrelaboralCp3) {
		this.indPrelaboralCp3 = indPrelaboralCp3;
	}

	public Integer getIndPrelaboralMe3() {
		return indPrelaboralMe3;
	}

	public void setIndPrelaboralMe3(Integer indPrelaboralMe3) {
		this.indPrelaboralMe3 = indPrelaboralMe3;
	}

	public Integer getIndPrelaboralCp4() {
		return indPrelaboralCp4;
	}

	public void setIndPrelaboralCp4(Integer indPrelaboralCp4) {
		this.indPrelaboralCp4 = indPrelaboralCp4;
	}

	public Integer getIndPrelaboralMe4() {
		return indPrelaboralMe4;
	}

	public void setIndPrelaboralMe4(Integer indPrelaboralMe4) {
		this.indPrelaboralMe4 = indPrelaboralMe4;
	}

	public Integer getIndPrelaboralCp5() {
		return indPrelaboralCp5;
	}

	public void setIndPrelaboralCp5(Integer indPrelaboralCp5) {
		this.indPrelaboralCp5 = indPrelaboralCp5;
	}

	public Integer getIndPrelaboralMe5() {
		return indPrelaboralMe5;
	}

	public void setIndPrelaboralMe5(Integer indPrelaboralMe5) {
		this.indPrelaboralMe5 = indPrelaboralMe5;
	}

	public Integer getIndPrelaboralCp6() {
		return indPrelaboralCp6;
	}

	public void setIndPrelaboralCp6(Integer indPrelaboralCp6) {
		this.indPrelaboralCp6 = indPrelaboralCp6;
	}

	public Integer getIndPrelaboralMe6() {
		return indPrelaboralMe6;
	}

	public void setIndPrelaboralMe6(Integer indPrelaboralMe6) {
		this.indPrelaboralMe6 = indPrelaboralMe6;
	}

	public Integer getIndPrelaboralCp7() {
		return indPrelaboralCp7;
	}

	public void setIndPrelaboralCp7(Integer indPrelaboralCp7) {
		this.indPrelaboralCp7 = indPrelaboralCp7;
	}

	public Integer getIndPrelaboralMe7() {
		return indPrelaboralMe7;
	}

	public void setIndPrelaboralMe7(Integer indPrelaboralMe7) {
		this.indPrelaboralMe7 = indPrelaboralMe7;
	}

	public Integer getIndPrelaboralCp8() {
		return indPrelaboralCp8;
	}

	public void setIndPrelaboralCp8(Integer indPrelaboralCp8) {
		this.indPrelaboralCp8 = indPrelaboralCp8;
	}

	public Integer getIndPrelaboralMe8() {
		return indPrelaboralMe8;
	}

	public void setIndPrelaboralMe8(Integer indPrelaboralMe8) {
		this.indPrelaboralMe8 = indPrelaboralMe8;
	}

	public Integer getIndPrelaboralCp9() {
		return indPrelaboralCp9;
	}

	public void setIndPrelaboralCp9(Integer indPrelaboralCp9) {
		this.indPrelaboralCp9 = indPrelaboralCp9;
	}

	public Integer getIndPrelaboralMe9() {
		return indPrelaboralMe9;
	}

	public void setIndPrelaboralMe9(Integer indPrelaboralMe9) {
		this.indPrelaboralMe9 = indPrelaboralMe9;
	}

	public Integer getIndPrelaboralCp10() {
		return indPrelaboralCp10;
	}

	public void setIndPrelaboralCp10(Integer indPrelaboralCp10) {
		this.indPrelaboralCp10 = indPrelaboralCp10;
	}

	public Integer getIndPrelaboralMe10() {
		return indPrelaboralMe10;
	}

	public void setIndPrelaboralMe10(Integer indPrelaboralMe10) {
		this.indPrelaboralMe10 = indPrelaboralMe10;
	}

	public Integer getIndPrelaboralCp11() {
		return indPrelaboralCp11;
	}

	public void setIndPrelaboralCp11(Integer indPrelaboralCp11) {
		this.indPrelaboralCp11 = indPrelaboralCp11;
	}

	public Integer getIndPrelaboralMe11() {
		return indPrelaboralMe11;
	}

	public void setIndPrelaboralMe11(Integer indPrelaboralMe11) {
		this.indPrelaboralMe11 = indPrelaboralMe11;
	}

	public Integer getIndPrelaboralCp12() {
		return indPrelaboralCp12;
	}

	public void setIndPrelaboralCp12(Integer indPrelaboralCp12) {
		this.indPrelaboralCp12 = indPrelaboralCp12;
	}

	public Integer getIndPrelaboralMe12() {
		return indPrelaboralMe12;
	}

	public void setIndPrelaboralMe12(Integer indPrelaboralMe12) {
		this.indPrelaboralMe12 = indPrelaboralMe12;
	}

	public Integer getIndPrelaboralCp13() {
		return indPrelaboralCp13;
	}

	public void setIndPrelaboralCp13(Integer indPrelaboralCp13) {
		this.indPrelaboralCp13 = indPrelaboralCp13;
	}

	public Integer getIndPrelaboralMe13() {
		return indPrelaboralMe13;
	}

	public void setIndPrelaboralMe13(Integer indPrelaboralMe13) {
		this.indPrelaboralMe13 = indPrelaboralMe13;
	}

	public Integer getIndPrelaboralCp14() {
		return indPrelaboralCp14;
	}

	public void setIndPrelaboralCp14(Integer indPrelaboralCp14) {
		this.indPrelaboralCp14 = indPrelaboralCp14;
	}

	public Integer getIndPrelaboralMe14() {
		return indPrelaboralMe14;
	}

	public void setIndPrelaboralMe14(Integer indPrelaboralMe14) {
		this.indPrelaboralMe14 = indPrelaboralMe14;
	}

	public Integer getIndPrelaboralCp15() {
		return indPrelaboralCp15;
	}

	public void setIndPrelaboralCp15(Integer indPrelaboralCp15) {
		this.indPrelaboralCp15 = indPrelaboralCp15;
	}

	public Integer getIndPrelaboralMe15() {
		return indPrelaboralMe15;
	}

	public void setIndPrelaboralMe15(Integer indPrelaboralMe15) {
		this.indPrelaboralMe15 = indPrelaboralMe15;
	}

	public Integer getIndPrelaboralCp16() {
		return indPrelaboralCp16;
	}

	public void setIndPrelaboralCp16(Integer indPrelaboralCp16) {
		this.indPrelaboralCp16 = indPrelaboralCp16;
	}

	public Integer getIndPrelaboralMe16() {
		return indPrelaboralMe16;
	}

	public void setIndPrelaboralMe16(Integer indPrelaboralMe16) {
		this.indPrelaboralMe16 = indPrelaboralMe16;
	}

	public Integer getIndPrelaboralCp17() {
		return indPrelaboralCp17;
	}

	public void setIndPrelaboralCp17(Integer indPrelaboralCp17) {
		this.indPrelaboralCp17 = indPrelaboralCp17;
	}

	public Integer getIndPrelaboralMe17() {
		return indPrelaboralMe17;
	}

	public void setIndPrelaboralMe17(Integer indPrelaboralMe17) {
		this.indPrelaboralMe17 = indPrelaboralMe17;
	}

	public Integer getIndPrelaboralCp18() {
		return indPrelaboralCp18;
	}

	public void setIndPrelaboralCp18(Integer indPrelaboralCp18) {
		this.indPrelaboralCp18 = indPrelaboralCp18;
	}

	public Integer getIndPrelaboralMe18() {
		return indPrelaboralMe18;
	}

	public void setIndPrelaboralMe18(Integer indPrelaboralMe18) {
		this.indPrelaboralMe18 = indPrelaboralMe18;
	}

}
