package pe.gob.trabajo.pcd.modelo.dominio;


/**
 * PersonaDiscapacidad generated by hbm2java
 */
public class PersonaDatosMedicos extends BeanEntidadGenericoAutogenerado
		implements java.io.Serializable {
	
	private static final long serialVersionUID = 2271877123168109831L;
	
	private Persona persona;
	private String condicionesAsociadas;
	
	private String problemasSalud;
	private String horarioMedicacion;
	private String tipoSeguroSalud;
	private String alteracionAuditiva;
	private String alteracionVisual;
	private String alteracionTactil;
	private String alteracionOlfativa;
	private String alteracionTermica;
	private String alteracionOtra;
	
	/**
	 * @return the persona
	 */
	public Persona getPersona() {
		return persona;
	}
	/**
	 * @param persona the persona to set
	 */
	public void setPersona(Persona persona) {
		this.persona = persona;
	}
	/**
	 * @return the condicionesAsociadas
	 */
	public String getCondicionesAsociadas() {
		return condicionesAsociadas;
	}
	/**
	 * @param condicionesAsociadas the condicionesAsociadas to set
	 */
	public void setCondicionesAsociadas(String condicionesAsociadas) {
		this.condicionesAsociadas = condicionesAsociadas;
	}
	/**
	 * @return the problemasSalud
	 */
	public String getProblemasSalud() {
		return problemasSalud;
	}
	/**
	 * @param problemasSalud the problemasSalud to set
	 */
	public void setProblemasSalud(String problemasSalud) {
		this.problemasSalud = problemasSalud;
	}
	/**
	 * @return the horarioMedicacion
	 */
	public String getHorarioMedicacion() {
		return horarioMedicacion;
	}
	/**
	 * @param horarioMedicacion the horarioMedicacion to set
	 */
	public void setHorarioMedicacion(String horarioMedicacion) {
		this.horarioMedicacion = horarioMedicacion;
	}
	/**
	 * @return the tipoSeguroSalud
	 */
	public String getTipoSeguroSalud() {
		return tipoSeguroSalud;
	}
	/**
	 * @param tipoSeguroSalud the tipoSeguroSalud to set
	 */
	public void setTipoSeguroSalud(String tipoSeguroSalud) {
		this.tipoSeguroSalud = tipoSeguroSalud;
	}
	/**
	 * @return the alteracionAuditiva
	 */
	public String getAlteracionAuditiva() {
		return alteracionAuditiva;
	}
	/**
	 * @param alteracionAuditiva the alteracionAuditiva to set
	 */
	public void setAlteracionAuditiva(String alteracionAuditiva) {
		this.alteracionAuditiva = alteracionAuditiva;
	}
	/**
	 * @return the alteracionVisual
	 */
	public String getAlteracionVisual() {
		return alteracionVisual;
	}
	/**
	 * @param alteracionVisual the alteracionVisual to set
	 */
	public void setAlteracionVisual(String alteracionVisual) {
		this.alteracionVisual = alteracionVisual;
	}
	/**
	 * @return the alteracionTactil
	 */
	public String getAlteracionTactil() {
		return alteracionTactil;
	}
	/**
	 * @param alteracionTactil the alteracionTactil to set
	 */
	public void setAlteracionTactil(String alteracionTactil) {
		this.alteracionTactil = alteracionTactil;
	}
	/**
	 * @return the alteracionOlfativa
	 */
	public String getAlteracionOlfativa() {
		return alteracionOlfativa;
	}
	/**
	 * @param alteracionOlfativa the alteracionOlfativa to set
	 */
	public void setAlteracionOlfativa(String alteracionOlfativa) {
		this.alteracionOlfativa = alteracionOlfativa;
	}
	/**
	 * @return the alteracionTermica
	 */
	public String getAlteracionTermica() {
		return alteracionTermica;
	}
	/**
	 * @param alteracionTermica the alteracionTermica to set
	 */
	public void setAlteracionTermica(String alteracionTermica) {
		this.alteracionTermica = alteracionTermica;
	}
	/**
	 * @return the alteracionOtra
	 */
	public String getAlteracionOtra() {
		return alteracionOtra;
	}
	/**
	 * @param alteracionOtra the alteracionOtra to set
	 */
	public void setAlteracionOtra(String alteracionOtra) {
		this.alteracionOtra = alteracionOtra;
	}
	
}
