package pe.gob.trabajo.pcd.modelo.dominio;

// Generated 27/01/2011 05:11:53 PM by Hibernate Tools 3.4.0.Beta1

/**
 * TiprfPrfsnalPreferencia generated by hbm2java
 */
public class Preferencia extends BeanEntidadGenerico implements java.io.Serializable {
	
	private static final long serialVersionUID = 5262995276660285312L;
	
	private PreferenciaId id;
	private Profesional profesional;
	private TipoPreferencia tipoPreferencia;
	
	private Area area;
	private Sector sector;
	private Ubigeo ciudad;
	private Long idSector;
	
	
	public PreferenciaId getId() {
		return this.id;
	}

	public void setId(PreferenciaId id) {
		this.id = id;
	}

	public Profesional getProfesional() {
		return profesional;
	}

	public void setProfesional(Profesional profesional) {
		this.profesional = profesional;
	}

	public TipoPreferencia getTipoPreferencia() {
		return tipoPreferencia;
	}

	public void setTipoPreferencia(TipoPreferencia tipoPreferencia) {
		this.tipoPreferencia = tipoPreferencia;
	}

	public Area getArea() {
		return area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	public Sector getSector() {
		return sector;
	}

	public void setSector(Sector sector) {
		this.sector = sector;
	}

	public Ubigeo getCiudad() {
		return ciudad;
	}

	public void setCiudad(Ubigeo ciudad) {
		this.ciudad = ciudad;
	}

	public Long getIdSector() {
		return idSector;
	}

	public void setIdSector(Long idSector) {
		this.idSector = idSector;
	}
	
}
