package pe.gob.trabajo.pcd.modelo.dominio;

// Generated 27/01/2011 05:11:53 PM by Hibernate Tools 3.4.0.Beta1

/**
 * TiprfPrfsnalPreferenciaId generated by hbm2java
 */
public class PreferenciaId implements java.io.Serializable {
	
	private static final long serialVersionUID = -4289702337165151550L;
	
	private Long idTpoPrfrnca;
	private Long idPrfrnca;
	private Long idPrfsnal;

	public PreferenciaId() {
	}

	public PreferenciaId(Long idTpoPrfrnca, Long idPrfrnca,
			Long idPrfsnal) {
		this.idTpoPrfrnca = idTpoPrfrnca;
		this.idPrfrnca = idPrfrnca;
		this.idPrfsnal = idPrfsnal;
	}

	public Long getIdTpoPrfrnca() {
		return this.idTpoPrfrnca;
	}

	public void setIdTpoPrfrnca(Long idTpoPrfrnca) {
		this.idTpoPrfrnca = idTpoPrfrnca;
	}

	public Long getIdPrfrnca() {
		return this.idPrfrnca;
	}

	public void setIdPrfrnca(Long idPrfrnca) {
		this.idPrfrnca = idPrfrnca;
	}

	public Long getIdPrfsnal() {
		return this.idPrfsnal;
	}

	public void setIdPrfsnal(Long idPrfsnal) {
		this.idPrfsnal = idPrfsnal;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PreferenciaId))
			return false;
		PreferenciaId castOther = (PreferenciaId) other;

		return ((this.getIdTpoPrfrnca() == castOther.getIdTpoPrfrnca()) || (this
				.getIdTpoPrfrnca() != null
				&& castOther.getIdTpoPrfrnca() != null && this
				.getIdTpoPrfrnca().equals(castOther.getIdTpoPrfrnca())))
				&& (this.getIdPrfrnca() == castOther.getIdPrfrnca())
				&& ((this.getIdPrfsnal() == castOther.getIdPrfsnal()) || (this
						.getIdPrfsnal() != null
						&& castOther.getIdPrfsnal() != null && this
						.getIdPrfsnal().equals(castOther.getIdPrfsnal())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getIdTpoPrfrnca() == null ? 0 : this.getIdTpoPrfrnca()
						.hashCode());
		result = 37 * result + this.getIdPrfrnca().intValue();
		result = 37 * result
				+ (getIdPrfsnal() == null ? 0 : this.getIdPrfsnal().hashCode());
		return result;
	}

}
