package pe.gob.trabajo.pcd.modelo.dominio;

// Generated 28/01/2011 10:09:44 AM by Hibernate Tools 3.4.0.Beta1

/**
 * TiprmRelacionTecnologiaId generated by hbm2java
 */
public class RelacionTecnologiaId implements java.io.Serializable {
	
	private static final long serialVersionUID = 4001511983508952696L;
	
	private long idEspecialidadOrigen;
	private long idEspecialidadDestino;
	private Long tipo;

	public RelacionTecnologiaId() {
	}

	public RelacionTecnologiaId(long idEspcaldadOrgen,
			long idEspcaldadDstno, Long tpo) {
		this.idEspecialidadOrigen = idEspcaldadOrgen;
		this.idEspecialidadDestino = idEspcaldadDstno;
		this.tipo = tpo;
	}

	public long getIdEspecialidadOrigen() {
		return this.idEspecialidadOrigen;
	}

	public void setIdEspecialidadOrigen(long idEspcaldadOrgen) {
		this.idEspecialidadOrigen = idEspcaldadOrgen;
	}

	public long getIdEspecialidadDestino() {
		return this.idEspecialidadDestino;
	}

	public void setIdEspecialidadDestino(long idEspcaldadDstno) {
		this.idEspecialidadDestino = idEspcaldadDstno;
	}

	public Long getTipo() {
		return this.tipo;
	}

	public void setTipo(Long tpo) {
		this.tipo = tpo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RelacionTecnologiaId))
			return false;
		RelacionTecnologiaId castOther = (RelacionTecnologiaId) other;

		return (this.getIdEspecialidadOrigen() == castOther.getIdEspecialidadOrigen())
				&& (this.getIdEspecialidadDestino() == castOther
						.getIdEspecialidadDestino())
				&& ((this.getTipo() == castOther.getTipo()) || (this.getTipo() != null
						&& castOther.getTipo() != null && this.getTipo().equals(
						castOther.getTipo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdEspecialidadOrigen();
		result = 37 * result + (int) this.getIdEspecialidadDestino();
		result = 37 * result
				+ (getTipo() == null ? 0 : this.getTipo().hashCode());
		return result;
	}

}
