package pe.gob.trabajo.pcd.modelo.dominio;

// Generated 27/01/2011 05:11:53 PM by Hibernate Tools 3.4.0.Beta1

import java.util.ArrayList;
import java.util.List;

/**
 * TiprmRolLaboral generated by hbm2java
 */
public class RolLaboral extends BeanEntidadGenericoAutogenerado implements java.io.Serializable {
	
	private static final long serialVersionUID = -7339635904435451275L;

	private RolLaboral rolLaboralPadre;
	
	private List<RolLaboral> rolesHijos = new ArrayList<RolLaboral>();

	public RolLaboral getRolLaboralPadre() {
		return rolLaboralPadre;
	}

	public void setRolLaboralPadre(RolLaboral rolLaboralPadre) {
		this.rolLaboralPadre = rolLaboralPadre;
	}

	public List<RolLaboral> getRolesHijos() {
		return rolesHijos;
	}

	public void setRolesHijos(List<RolLaboral> rolesHijos) {
		this.rolesHijos = rolesHijos;
	}

}
