package pe.gob.trabajo.pcd.modelo.dominio;

// Generated 27/01/2011 05:11:53 PM by Hibernate Tools 3.4.0.Beta1


/**
 * TiprmSector generated by hbm2java
 */
public class Sector extends BeanEntidadGenericoAutogenerado implements java.io.Serializable {
	
	private static final long serialVersionUID = 5145983683911688037L;
	
	private String flgAct;
	private Long nivel;
	
	public String getFlgAct() {
		return flgAct;
	}
	public void setFlgAct(String flgAct) {
		this.flgAct = flgAct;
	}
	public Long getNivel() {
		return nivel;
	}
	public void setNivel(Long nivel) {
		this.nivel = nivel;
	}
	
}
