package pe.gob.trabajo.pcd.modelo.dominio;

import java.util.ArrayList;
import java.util.List;

// Generated 27/01/2011 05:11:53 PM by Hibernate Tools 3.4.0.Beta1


/**
 * TiprmTipoContacto generated by hbm2java
 */
public class TipoContacto extends BeanEntidadGenericoAutogenerado implements java.io.Serializable {
	
	private static final long serialVersionUID = -3995622441833048413L;
	
	private List<TipoContacto> tipoContacto = new ArrayList<TipoContacto>();
//	public List<TipoContacto> getValoresContacto() {
//		ArrayList<TipoContacto> lista = new ArrayList<TipoContacto>();
//
//		for (TipoContacto tiposContacto : tipoContacto) {
//			if (tiposContacto != null) {
//				lista.add(tiposContacto);
//			}
//		}
//		return lista;
//	}

	public List<TipoContacto> getTipoContacto() {
		return tipoContacto;
	}

	public void setTipoContacto(List<TipoContacto> tipoContacto) {
		this.tipoContacto = tipoContacto;
	}
	public List<TipoContacto> getValoresTipoContacto() {
		ArrayList<TipoContacto> lista = new ArrayList<TipoContacto>();

		for (TipoContacto tipoContactos : tipoContacto) {
			if (tipoContactos != null) {
				lista.add(tipoContactos);
			}
		}
		return lista;
	}

}
