package pe.gob.trabajo.pcd.modelo.dominio;

// Generated 27/01/2011 05:11:53 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TiprmTipoPreferencia generated by hbm2java
 */
public class TipoPreferencia extends BeanEntidadGenericoAutogenerado implements java.io.Serializable {

	private static final long serialVersionUID = -9053644899773501494L;
	
	public TipoPreferencia() {
		
	}
	
	public TipoPreferencia(Long id, String descripcion) {
		setId(id);
		setDescripcion(descripcion);
	}
	
}
