package pe.gob.trabajo.pcd.modelo.dominio;

// Generated 28/01/2011 10:09:44 AM by Hibernate Tools 3.4.0.Beta1

import java.util.ArrayList;
import java.util.List;

/**
 * TiprmTipoRelacionTecnologia generated by hbm2java
 */
public class TipoRelacionTecnologia extends BeanEntidadGenericoAutogenerado implements java.io.Serializable {
	
	private static final long serialVersionUID = -2862230727552420383L;
	
	private List<RelacionTecnologia> relacionTecnologias = new ArrayList<RelacionTecnologia>();

	public List<RelacionTecnologia> getRelacionTecnologias() {
		return relacionTecnologias;
	}

	public void setRelacionTecnologias(List<RelacionTecnologia> relacionTecnologias) {
		this.relacionTecnologias = relacionTecnologias;
	}

}
