package pe.gob.trabajo.pcd.modelo.dominio;


/**
 * TiprmPersona generated by hbm2java
 */
public class Postulacion extends BeanEntidadGenericoAutogenerado implements java.io.Serializable {
	private static final long serialVersionUID = -4705668943173074878L;
	private Pedido  pedido;
	private Profesional profesional;
	public Pedido getPedido() {
		return pedido;
	}
	public void setPedido(Pedido pedido) {
		this.pedido = pedido;
	}
	public Profesional getProfesional() {
		return profesional;
	}
	public void setProfesional(Profesional profesional) {
		this.profesional = profesional;
	}

}
