package pe.gob.trabajo.pcd.modelo.dominio;

// Generated 27/01/2011 05:11:53 PM by Hibernate Tools 3.4.0.Beta1


/**
 * TiprmUbigeo generated by hbm2java
 */
public class Ubigeo extends BeanEntidadGenericoAutogenerado implements java.io.Serializable {
	
	private static final long serialVersionUID = -2379846552061705925L;
	
	private String idDprtmnto;
	private String idPrvnca;
	private String idDstrto;
	private String nombre;
	private Ubigeo ubigeoRegion;
	private Ubigeo ubigeoProvincia;
	private Ubigeo ubigeoDistrito;
	
	
	public Ubigeo() {
		idDprtmnto = "00";
		idPrvnca = "00";
		idDstrto = "00";
	}
	
	public String getIdDprtmnto() {
		return idDprtmnto;
	}
	public void setIdDprtmnto(String idDprtmnto) {
		this.idDprtmnto = idDprtmnto;
	}
	public String getIdPrvnca() {
		return idPrvnca;
	}
	public void setIdPrvnca(String idPrvnca) {
		this.idPrvnca = idPrvnca;
	}
	public String getIdDstrto() {
		return idDstrto;
	}
	public void setIdDstrto(String idDstrto) {
		this.idDstrto = idDstrto;
	}
	public String getNombre() {
		return nombre;
	}
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	
	public String getCodigoLugar() {
		String codigo = getIdDstrto();
		if ("00".equals(getIdDstrto())) {
			codigo = getIdPrvnca();
		} else if ("00".equals(getIdPrvnca())) {
			codigo = getIdDprtmnto();
		}
		return codigo;
	}
	
	public String getTipoLugar() {
		String tipo = "idDstrto";
		if ("00".equals(getIdDstrto())) {
			tipo = "idPrvnca";
		} else if ("00".equals(getIdPrvnca())) {
			tipo = "idDprtmnto";
		}
		return tipo;
	}
	
	public boolean isDepartamento() {
		boolean retorno = false;
		if (!isProvincia() && !isDistrito()) {
			retorno = true;
		}
		return retorno;
	}
	
	public boolean isProvincia() {
		boolean retorno = false;
		if (!"00".equals(getIdPrvnca()) && !isDistrito()) {
			retorno = true;
		}
		return retorno;
	}
	
	public boolean isDistrito() {
		boolean retorno = false;
		if (!"00".equals(getIdDstrto())) {
			retorno = true;
		}
		return retorno;
	}

	public Ubigeo getUbigeoRegion() {
		return ubigeoRegion;
	}

	public void setUbigeoRegion(Ubigeo ubigeoRegion) {
		this.ubigeoRegion = ubigeoRegion;
	}

	public Ubigeo getUbigeoProvincia() {
		return ubigeoProvincia;
	}

	public void setUbigeoProvincia(Ubigeo ubigeoProvincia) {
		this.ubigeoProvincia = ubigeoProvincia;
	}

	public Ubigeo getUbigeoDistrito() {
		return ubigeoDistrito;
	}

	public void setUbigeoDistrito(Ubigeo ubigeoDistrito) {
		this.ubigeoDistrito = ubigeoDistrito;
	}
	
}
