package pe.gob.trabajo.pcd.modelo.dominio;

// Generated 27/01/2011 05:11:53 PM by Hibernate Tools 3.4.0.Beta1


/**
 * TiprmTipoDocumentoIdentidad generated by hbm2java
 */
public class TipoDocumentoIdentidad extends BeanEntidadGenericoAutogenerado implements java.io.Serializable {
	
	private static final long serialVersionUID = -6642373333726630820L;
	

}
